<a href="https://colab.research.google.com/github/1329darssheelaravi-jpg/sharing-github/blob/main/MEFSAT_compounds_screening.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# ============================================================
# VS-04 MEFSAT Batch 03 — CELL 1
# Confirm screening input
# ============================================================

from google.colab import drive

drive.mount('/content/drive')

print("Google Drive mounted successfully.")

Mounted at /content/drive
Google Drive mounted successfully.

In [ ]:
# ============================================================
# VS-04 MEFSAT Batch 03 — CELL 1A
# Locate Batch 03 screening input
# ============================================================

import os

BASE_DIR = "/content/drive/MyDrive/PhD_ML_Project"

print("=" * 70)
print("SEARCHING FOR MEFSAT BATCH 03 FILES")
print("=" * 70)

matches = []

for root, dirs, files in os.walk(BASE_DIR):
    for file in files:
        if "Batch_03" in file or "Batch03" in file or "Batch 03" in file:
            matches.append(os.path.join(root, file))

if matches:
    print(f"\nFound {len(matches)} possible Batch 03 file(s):\n")
    for path in matches:
        print(path)
else:
    print("\nNo Batch 03 files found using the filename search.")

print("=" * 70)

======================================================================
SEARCHING FOR MEFSAT BATCH 03 FILES
======================================================================

Found 8 possible Batch 03 file(s):

/content/drive/MyDrive/PhD_ML_Project/Notebooks/Colab Notebooks/VS04_Batch03_MEFSAT_Data_Preparation .ipynb
/content/drive/MyDrive/PhD_ML_Project/VS-04_Batch_03_MEFSAT/02_Processing/Batch03_MEFSAT_Ganoderma_lucidum_Association_Extract.csv
/content/drive/MyDrive/PhD_ML_Project/VS-04_Batch_03_MEFSAT/02_Processing/Batch03_MEFSAT_Ganoderma_lucidum_PreQC.csv
/content/drive/MyDrive/PhD_ML_Project/VS-04_Batch_03_MEFSAT/02_Processing/Batch03_MEFSAT_Glucidum_Final_QC_277.csv
/content/drive/MyDrive/PhD_ML_Project/VS-04_Batch_03_MEFSAT/02_Processing/Batch03_MEFSAT_Glucidum_Screening_Library_275.csv
/content/drive/MyDrive/PhD_ML_Project/VS-04_Batch_03_MEFSAT/02_Processing/Batch03_MEFSAT_Glucidum_Morgan2048_Final.csv
/content/drive/MyDrive/PhD_ML_Project/VS-04_Batch_03_MEFSAT/03_Prediction/Batch03_MEFSAT_Glucidum_Master_Predictions.csv
/content/drive/MyDrive/PhD_ML_Project/VS-04_Batch_03_MEFSAT/03_Prediction/Batch03_MEFSAT_Glucidum_Predicted_Hits.csv
======================================================================

In [ ]:
# ============================================================
# VS-04 MEFSAT Batch 03 — CELL 2
# Load and validate the 275-compound screening library
# ============================================================

import pandas as pd

INPUT_FILE = (
    "/content/drive/MyDrive/PhD_ML_Project/"
    "VS-04_Batch_03_MEFSAT/02_Processing/"
    "Batch03_MEFSAT_Glucidum_Screening_Library_275.csv"
)

df = pd.read_csv(INPUT_FILE)

print("=" * 70)
print("VS-04 MEFSAT BATCH 03 — SCREENING LIBRARY QC")
print("=" * 70)

print(f"Number of compounds : {len(df)}")
print(f"Number of columns   : {len(df.columns)}")

print("\nColumns:")
for i, col in enumerate(df.columns):
    print(f"{i:2d} : {col}")

print("\nMissing values:")
print(df.isna().sum())

print("\nDuplicate complete rows:")
print(df.duplicated().sum())

print("\nFirst 5 rows:")
display(df.head())

print("\nLast 5 rows:")
display(df.tail())

print("=" * 70)

======================================================================
VS-04 MEFSAT BATCH 03 — SCREENING LIBRARY QC
======================================================================
Number of compounds : 275
Number of columns   : 71

Columns:
 0 : Serial_Number
 1 : Secondary_Metabolite_Identifier
 2 : Secondary_Metabolite_Name
 3 : PubChem_Compound_Identifier
 4 : Kingdom
 5 : Superclass
 6 : Class
 7 : Subclass
 8 : Chemical_Formula
 9 : Molecular_Weight
10 : Exact_Molecular_Weight
11 : LogP
12 : Molar_Refractivity
13 : Topological_Polar_Surface_Area
14 : Number_Of_Hydrogen_Bond_Donors
15 : Number_Of_Hydrogen_Bond_Acceptors
16 : Number_Of_Chiral_Carbons
17 : Number_Of_Carbon_Atoms
18 : Number_Of_SP_Hybridized_Carbon_Atoms
19 : Number_Of_SP2_Hybridized_Carbon_Atoms
20 : Number_Of_SP3_Hybridized_Carbon_Atoms
21 : Fraction_Of_SP3_Hybridized_Carbon_Atoms
22 : Fraction_Of_Chiral_Carbon_Atoms
23 : Number_Of_Heavy_Atom
24 : Number_Of_Nitrogen_Atoms
25 : Number_Of_Sulphur_Atoms
26 : Number_Of_Heteroatoms
27 : Number_Of_Rotatable_Bonds
28 : Number_Of_Aliphatic_Carbon_Cycles
29 : Number_Of_Aliphatic_Heterocycles
30 : Number_Of_Aliphatic_Rings
31 : Number_Of_Aromatic_Carbon_Cycles
32 : Number_Of_Aromatic_Heterocycles
33 : Number_Of_Aromatic_Rings
34 : Total_Number_Of_Rings
35 : Number_Of_Saturated_Carbon_Cycles
36 : Number_Of_Saturated_Heterocycles
37 : Number_Of_Saturated_Rings
38 : Smallest_Set_Of_Smallest_Rings_SSSR
39 : Lipinski_RO5_Violations
40 : Lipinski_Filter
41 : Ghose_Filter_Violations
42 : Ghose_Filter
43 : Veber_Filter
44 : Egan_Filter
45 : GSK_4_400_Filter
46 : Pfizer_3_75_Filter
47 : QEDw
48 : QEDuw
49 : Shape_Complexity
50 : Stereochemical_Complexity
51 : ESOL_Class
52 : Silicos_IT_Class
53 : GI_Absorption
54 : BBB_Permeant
55 : Pgp_Substrate
56 : CYP1A2_Inhibitor
57 : CYP2C19_Inhibitor
58 : CYP2C9_Inhibitor
59 : CYP2D6_Inhibitor
60 : CYP3A4_Inhibitor
61 : Log_Kp_Cm_S
62 : Bioavailability_Score
63 : PAINS_Alerts
64 : Brenk_Alerts
65 : Leadlikeness_Violations
66 : SMILES
67 : Screening_Decision
68 : Exclusion_Reason
69 : Structural_QC
70 : Canonical_SMILES

Missing values:
Serial_Number                        0
Secondary_Metabolite_Identifier      0
Secondary_Metabolite_Name            0
PubChem_Compound_Identifier         53
Kingdom                              0
                                  ...
SMILES                               0
Screening_Decision                   0
Exclusion_Reason                   275
Structural_QC                        0
Canonical_SMILES                     0
Length: 71, dtype: int64

Duplicate complete rows:
0

First 5 rows:

,Serial_Number,Secondary_Metabolite_Identifier,Secondary_Metabolite_Name,PubChem_Compound_Identifier,Kingdom,Superclass,Class,Subclass,Chemical_Formula,Molecular_Weight,...,Log_Kp_Cm_S,Bioavailability_Score,PAINS_Alerts,Brenk_Alerts,Leadlikeness_Violations,SMILES,Screening_Decision,Exclusion_Reason,Structural_QC,Canonical_SMILES
0,48,MSID000048,(-)-Chizhine A,CID_139587927,Organic compounds,Organic oxygen compounds,Organooxygen compounds,Carbonyl compounds,C16H18O5,290.315,...,-6.01,0.55,0,2,0,CC(=C[C@@H]1OC(=O)[C@H](C1)CC(=O)c1cc(O)ccc1O)C,Include,NaN,Valid,CC(C)=C[C@H]1C[C@H](CC(=O)c2cc(O)ccc2O)C(=O)O1
1,49,MSID000049,(-)-Chizhine B,CID_101905608,Organic compounds,Organic oxygen compounds,Organooxygen compounds,Carbonyl compounds,C16H18O5,290.315,...,-6.01,0.55,0,2,0,CC(=C[C@H]1OC(=O)[C@H](C1)CC(=O)c1cc(O)ccc1O)C,Include,NaN,Valid,CC(C)=C[C@@H]1C[C@H](CC(=O)c2cc(O)ccc2O)C(=O)O1
2,50,MSID000050,(+)-Chizhine A,CID_101905607,Organic compounds,Organic oxygen compounds,Organooxygen compounds,Carbonyl compounds,C16H18O5,290.315,...,-6.01,0.55,0,2,0,CC(=C[C@H]1OC(=O)[C@@H](C1)CC(=O)c1cc(O)ccc1O)C,Include,NaN,Valid,CC(C)=C[C@@H]1C[C@@H](CC(=O)c2cc(O)ccc2O)C(=O)O1
3,51,MSID000051,(+)-Chizhine B,CID_139583972,Organic compounds,Organic oxygen compounds,Organooxygen compounds,Carbonyl compounds,C16H18O5,290.315,...,-6.01,0.55,0,2,0,CC(=C[C@@H]1OC(=O)[C@@H](C1)CC(=O)c1cc(O)ccc1O)C,Include,NaN,Valid,CC(C)=C[C@H]1C[C@@H](CC(=O)c2cc(O)ccc2O)C(=O)O1
4,52,MSID000052,(-)-Chizhine C,CID_139585585,Organic compounds,Organic oxygen compounds,Organooxygen compounds,Carbonyl compounds,C16H18O6,306.314,...,-6.56,0.55,0,2,0,CC(=C)[C@@H]1CC[C@](C(=O)O1)(O)CC(=O)c1cc(O)ccc1O,Include,NaN,Valid,C=C(C)[C@@H]1CC[C@](O)(CC(=O)c2cc(O)ccc2O)C(=O)O1

Last 5 rows:

,Serial_Number,Secondary_Metabolite_Identifier,Secondary_Metabolite_Name,PubChem_Compound_Identifier,Kingdom,Superclass,Class,Subclass,Chemical_Formula,Molecular_Weight,...,Log_Kp_Cm_S,Bioavailability_Score,PAINS_Alerts,Brenk_Alerts,Leadlikeness_Violations,SMILES,Screening_Decision,Exclusion_Reason,Structural_QC,Canonical_SMILES
270,1813,MSID001813,Ganoderique acid V,CID_139585281,Organic compounds,Lipids and lipid-like molecules,Prenol lipids,Triterpenoids,C32H48O6,528.730,...,-5.81,0.56,0,2,2,CC(=O)O[C@H]1C[C@@H]([C@@]2([C@]1(C)C1=C(CC2)[...,Include,NaN,Valid,CC(=O)O[C@H]1C[C@H]([C@H](C)CC/C=C(\C)C(=O)O)[...
271,1816,MSID001816,6-Dehydrocerevisterol,CID_146157297,Organic compounds,Lipids and lipid-like molecules,Steroids and steroid derivatives,Ergostane steroids,C28H44O3,428.657,...,-4.70,0.55,0,1,2,OC1CC[C@]2([C@@](C1)(O)C(=O)C=C1C2CC[C@]2(C1CC...,Include,NaN,Valid,CC(C)C(C)C=CC(C)C1CCC2C3=CC(=O)[C@@]4(O)CC(O)C...
272,1817,MSID001817,beta-Sitosterol,CID_222284,Organic compounds,Lipids and lipid-like molecules,Steroids and steroid derivatives,Stigmastanes and derivatives,C29H50O,414.718,...,-2.20,0.55,0,1,2,CC[C@@H](C(C)C)CC[C@H]([C@H]1CC[C@@H]2[C@]1(C)...,Include,NaN,Valid,CC[C@H](CC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C...
273,1818,MSID001818,"22,23-Dihydroergosterol",CID_5326970,Organic compounds,Lipids and lipid-like molecules,Steroids and steroid derivatives,Ergostane steroids,C28H46O,398.675,...,-2.90,0.55,0,0,2,O[C@H]1CC[C@]2(C(=CC=C3[C@@H]2CC[C@]2([C@H]3CC...,Include,NaN,Valid,CC(C)[C@@H](C)CC[C@@H](C)[C@H]1CC[C@H]2C3=CC=C...
274,1826,MSID001826,Lucidenic acid O,CID_9847846,Organic compounds,Lipids and lipid-like molecules,Steroids and steroid derivatives,Oxosteroids,C27H40O7,476.610,...,-7.76,0.56,0,1,1,OC[C@]1(C)[C@@H](O)CC[C@]2([C@H]1C[C@H](O)C1=C...,Include,NaN,Valid,C=C(CCC(=O)O)[C@H]1C[C@H](O)[C@@]2(C)C3=C(C(=O...

======================================================================

In [ ]:
# ============================================================
# VS-04 MEFSAT Batch 03 — CELL 3
# Confirm final screening eligibility
# ============================================================

print("=" * 70)
print("VS-04 MEFSAT BATCH 03 — ELIGIBILITY QC")
print("=" * 70)

print("\nScreening_Decision:")
print(df["Screening_Decision"].value_counts(dropna=False))

print("\nStructural_QC:")
print(df["Structural_QC"].value_counts(dropna=False))

print("\nMissing SMILES:")
print(df["SMILES"].isna().sum())

print("\nMissing Canonical_SMILES:")
print(df["Canonical_SMILES"].isna().sum())

print("\nNumber of unique Secondary Metabolite Identifiers:")
print(df["Secondary_Metabolite_Identifier"].nunique())

print("\nNumber of unique Canonical SMILES:")
print(df["Canonical_SMILES"].nunique())

print("=" * 70)

======================================================================
VS-04 MEFSAT BATCH 03 — ELIGIBILITY QC
======================================================================

Screening_Decision:
Screening_Decision
Include    275
Name: count, dtype: int64

Structural_QC:
Structural_QC
Valid    275
Name: count, dtype: int64

Missing SMILES:
0

Missing Canonical_SMILES:
0

Number of unique Secondary Metabolite Identifiers:
275

Number of unique Canonical SMILES:
275
======================================================================

In [ ]:
# ============================================================
# VS-04 MEFSAT Batch 03 — CELL 4
# Morgan fingerprint configuration QC
# ============================================================

MORGAN_RADIUS = 2
MORGAN_BITS = 2048

print("=" * 70)
print("VS-04 MEFSAT BATCH 03 — MORGAN CONFIGURATION")
print("=" * 70)

print(f"Morgan radius : {MORGAN_RADIUS}")
print(f"Morgan bits   : {MORGAN_BITS}")
print("Fingerprint type: Morgan")
print("Input column    : Canonical_SMILES")

assert MORGAN_RADIUS == 2
assert MORGAN_BITS == 2048

print("\nConfiguration checks:")
print("✓ Radius = 2")
print("✓ Bits = 2048")
print("✓ Input = Canonical_SMILES")

print("\nNo fingerprints generated.")
print("No models loaded.")
print("No predictions performed.")

print("=" * 70)

======================================================================
VS-04 MEFSAT BATCH 03 — MORGAN CONFIGURATION
======================================================================
Morgan radius : 2
Morgan bits   : 2048
Fingerprint type: Morgan
Input column    : Canonical_SMILES

Configuration checks:
✓ Radius = 2
✓ Bits = 2048
✓ Input = Canonical_SMILES

No fingerprints generated.
No models loaded.
No predictions performed.
======================================================================

In [ ]:
# ============================================================
# VS-04 MEFSAT Batch 03 — CELL 5
# Validate canonical SMILES with RDKit
# ============================================================

!pip install rdkit
from rdkit import Chem

print("=" * 70)
print("VS-04 MEFSAT BATCH 03 — RDKit MOLECULE VALIDATION")
print("=" * 70)

# Convert canonical SMILES to RDKit Mol objects
molecules = [
    Chem.MolFromSmiles(smiles)
    for smiles in df["Canonical_SMILES"]
]

# Count parsing failures
invalid_indices = [
    i for i, mol in enumerate(molecules)
    if mol is None
]

print(f"Total compounds checked : {len(molecules)}")
print(f"Valid RDKit molecules    : {len(molecules) - len(invalid_indices)}")
print(f"Invalid RDKit molecules  : {len(invalid_indices)}")

if invalid_indices:
    print("\nInvalid molecule indices:")
    print(invalid_indices)

    print("\nCorresponding compound information:")
    display(
        df.iloc[invalid_indices][
            [
                "Serial_Number",
                "Secondary_Metabolite_Identifier",
                "Secondary_Metabolite_Name",
                "Canonical_SMILES"
            ]
        ]
    )
else:
    print("\n✓ All 275 canonical SMILES successfully parsed by RDKit.")

print("\nNo Morgan fingerprints generated.")
print("No models loaded.")
print("No predictions performed.")

print("=" * 70)

Collecting rdkit
  Downloading rdkit-2026.3.6-cp313-cp313-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from rdkit) (2.1.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.13/dist-packages (from rdkit) (11.3.0)
Downloading rdkit-2026.3.6-cp313-cp313-manylinux_2_28_x86_64.whl (38.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.1/38.1 MB 33.7 MB/s eta 0:00:00
Installing collected packages: rdkit
Successfully installed rdkit-2026.3.6
======================================================================
VS-04 MEFSAT BATCH 03 — RDKit MOLECULE VALIDATION
======================================================================
Total compounds checked : 275
Valid RDKit molecules    : 275
Invalid RDKit molecules  : 0

✓ All 275 canonical SMILES successfully parsed by RDKit.

No Morgan fingerprints generated.
No models loaded.
No predictions performed.
======================================================================

In [ ]:
# ============================================================
# VS-04 MEFSAT Batch 03 — CELL 6
# Generate Morgan fingerprints
# ============================================================

from rdkit.Chem import rdFingerprintGenerator
import numpy as np

print("=" * 70)
print("VS-04 MEFSAT BATCH 03 — MORGAN FINGERPRINT GENERATION")
print("=" * 70)

# Frozen fingerprint specification
MORGAN_RADIUS = 2
MORGAN_BITS = 2048

# Create Morgan fingerprint generator
morgan_generator = rdFingerprintGenerator.GetMorganGenerator(
    radius=MORGAN_RADIUS,
    fpSize=MORGAN_BITS
)

# Generate fingerprints from the already validated RDKit molecules
fingerprints = np.array([
    morgan_generator.GetFingerprintAsNumPy(mol)
    for mol in molecules
], dtype=np.uint8)

print(f"Number of compounds : {fingerprints.shape[0]}")
print(f"Number of features  : {fingerprints.shape[1]}")
print(f"Data type           : {fingerprints.dtype}")

print("\nExpected:")
print("Compounds = 275")
print("Features  = 2048")

print("\nFingerprint generation complete.")
print("No models loaded.")
print("No predictions performed.")

print("=" * 70)

======================================================================
VS-04 MEFSAT BATCH 03 — MORGAN FINGERPRINT GENERATION
======================================================================
Number of compounds : 275
Number of features  : 2048
Data type           : uint8

Expected:
Compounds = 275
Features  = 2048

Fingerprint generation complete.
No models loaded.
No predictions performed.
======================================================================

In [ ]:
# ============================================================
# VS-04 MEFSAT Batch 03 — CELL 7
# Morgan fingerprint integrity QC
# ============================================================

print("=" * 70)
print("VS-04 MEFSAT BATCH 03 — FINGERPRINT INTEGRITY QC")
print("=" * 70)

# Basic shape checks
assert fingerprints.shape == (275, 2048), (
    f"Unexpected fingerprint shape: {fingerprints.shape}"
)

# Check for missing/non-finite values
nan_count = np.isnan(fingerprints).sum()
inf_count = np.isinf(fingerprints).sum()

# Check unique values present
unique_values = np.unique(fingerprints)

# Number of active bits per compound
active_bits = fingerprints.sum(axis=1)

print(f"Fingerprint matrix shape : {fingerprints.shape}")
print(f"NaN values               : {nan_count}")
print(f"Infinite values          : {inf_count}")
print(f"Unique values            : {unique_values}")
print(f"Minimum active bits      : {active_bits.min()}")
print(f"Maximum active bits      : {active_bits.max()}")
print(f"Mean active bits         : {active_bits.mean():.2f}")

print("\nIntegrity checks:")

if fingerprints.shape == (275, 2048):
    print("✓ Correct matrix dimensions")
else:
    print("✗ Incorrect matrix dimensions")

if nan_count == 0:
    print("✓ No NaN values")
else:
    print("✗ NaN values detected")

if inf_count == 0:
    print("✓ No infinite values")
else:
    print("✗ Infinite values detected")

if np.all(np.isin(unique_values, [0, 1])):
    print("✓ Binary fingerprint values confirmed")
else:
    print("✗ Unexpected fingerprint values detected")

if np.all(active_bits > 0):
    print("✓ Every compound has at least one active Morgan bit")
else:
    print("✗ At least one compound has zero active bits")

print("\nNo models loaded.")
print("No predictions performed.")

print("=" * 70)

======================================================================
VS-04 MEFSAT BATCH 03 — FINGERPRINT INTEGRITY QC
======================================================================
Fingerprint matrix shape : (275, 2048)
NaN values               : 0
Infinite values          : 0
Unique values            : [0 1]
Minimum active bits      : 22
Maximum active bits      : 73
Mean active bits         : 58.29

Integrity checks:
✓ Correct matrix dimensions
✓ No NaN values
✓ No infinite values
✓ Binary fingerprint values confirmed
✓ Every compound has at least one active Morgan bit

No models loaded.
No predictions performed.
======================================================================

In [ ]:
# ============================================================
# VS-04 MEFSAT Batch 03 — CELL 8
# Locate frozen VS-04 prediction models
# ============================================================

import os

BASE_DIR = "/content/drive/MyDrive/PhD_ML_Project"

print("=" * 70)
print("VS-04 MEFSAT BATCH 03 — FROZEN MODEL SEARCH")
print("=" * 70)

# Search for model files associated with VS-04
model_extensions = (".pkl", ".joblib")

model_files = []

for root, dirs, files in os.walk(BASE_DIR):
    for file in files:
        if file.lower().endswith(model_extensions):
            model_files.append(os.path.join(root, file))

print(f"\nTotal model files found: {len(model_files)}")

print("\nModel files:")
for path in sorted(model_files):
    print(path)

print("=" * 70)

======================================================================
VS-04 MEFSAT BATCH 03 — FROZEN MODEL SEARCH
======================================================================

Total model files found: 38

Model files:
/content/drive/MyDrive/PhD_ML_Project/Models/Stage 1/Dataset 1/Random_Forest1_Morgan.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/Stage 1/Dataset 1/Random_ForestRDKit 1.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/Stage 1/Dataset 1/SVM1_Morgan.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/Stage 1/Dataset 1/SVMRDKit1.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/Stage 1/Dataset 1/XGBoost1_Morgan.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/Stage 1/Dataset 1/XGBoostRDKit1.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/Stage 1/Dataset 2/Random_Forest2_Morgan.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/Stage 1/Dataset 2/Random_ForestRDKit2.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/Stage 1/Dataset 2/SVM2_Morgan.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/Stage 1/Dataset 2/SVMRDKit2.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/Stage 1/Dataset 2/XGBoost2_Morgan.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/Stage 1/Dataset 2/XGBoostRDKit2.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/Stage 1/Dataset 3/Random_Forest3_Morgan.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/Stage 1/Dataset 3/Random_ForestRDKit3.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/Stage 1/Dataset 3/SVM3_Morgan.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/Stage 1/Dataset 3/SVMRDKit3.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/Stage 1/Dataset 3/XGBoost3_Morgan.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/Stage 1/Dataset 3/XGBoostRDKit3.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/Stage 1/Random_Forest.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/Stage 1/XGBoost.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/Stage_2/RandomForest/Random_Forest_Ratio_1_5.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/Stage_2/XGBoost/Dataset_Ratio_1_10_XGBoost.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/Stage_2/XGBoost/Dataset_Ratio_1_1_XGBoost.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/Stage_2/XGBoost/Dataset_Ratio_1_2_XGBoost.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/Stage_2/XGBoost/Dataset_Ratio_1_3_XGBoost.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/Stage_2/XGBoost/Dataset_Ratio_1_4_XGBoost.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/Stage_2/XGBoost/Dataset_Ratio_1_5_XGBoost.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/XGBoost/5HT6/5HT6_XGBoost.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/XGBoost/AChE/AChE_XGBoost.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/XGBoost/BChE/BChE_XGBoost.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/XGBoost/GSK3B/GSK3B_XGBoost.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/XGBoost/M2/M2_XGBoost.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/XGBoost/MAOB/MAOB_XGBoost.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/XGBoost/NMDAR/NMDAR_XGBoost.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/XGBoost/PDE/PDE_XGBoost.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/XGBoost/TNFA/TNFA_XGBoost.pkl
/content/drive/MyDrive/PhD_ML_Project/Models/XGBoost/iNOS/iNOS_XGBoost.pkl
/content/drive/MyDrive/PhD_ML_Project/Random_ForestRDKit1.pkl
======================================================================

In [ ]:
# ============================================================
# VS-04 MEFSAT Batch 03 — CELL 9
# Frozen model compatibility QC
# ============================================================

import joblib
import os

MODEL_DIR = "/content/drive/MyDrive/PhD_ML_Project/Models/XGBoost"

TARGETS = [
    "AChE",
    "BChE",
    "M2",
    "NMDAR",
    "5HT6",
    "GSK3B",
    "MAOB",
    "PDE",
    "TNFA",
    "iNOS"
]

print("=" * 70)
print("VS-04 MEFSAT BATCH 03 — FROZEN MODEL COMPATIBILITY QC")
print("=" * 70)

frozen_models = {}

for target in TARGETS:

    model_path = os.path.join(
        MODEL_DIR,
        target,
        f"{target}_XGBoost.pkl"
    )

    print(f"\n{'-' * 70}")
    print(f"Target: {target}")
    print(f"Model : {model_path}")

    if not os.path.exists(model_path):
        print("✗ MODEL FILE NOT FOUND")
        continue

    model = joblib.load(model_path)
    frozen_models[target] = model

    print(f"Model class       : {type(model).__name__}")

    # Feature-count compatibility
    if hasattr(model, "n_features_in_"):
        print(f"Expected features : {model.n_features_in_}")
    else:
        print("Expected features : attribute not available")

    # XGBoost-specific information where available
    if hasattr(model, "get_booster"):
        booster = model.get_booster()
        print(f"Booster features  : {booster.num_features()}")

    print("✓ Model loaded")
    print("✓ No prediction performed")

print("\n" + "=" * 70)
print("MODEL COMPATIBILITY SUMMARY")
print("=" * 70)

print(f"Models successfully loaded: {len(frozen_models)}")
print(f"Expected fingerprint features: {fingerprints.shape[1]}")

print("=" * 70)

======================================================================
VS-04 MEFSAT BATCH 03 — FROZEN MODEL COMPATIBILITY QC
======================================================================

----------------------------------------------------------------------
Target: AChE
Model : /content/drive/MyDrive/PhD_ML_Project/Models/XGBoost/AChE/AChE_XGBoost.pkl

/usr/lib/python3.13/pickle.py:1754: UserWarning: [08:02:08] WARNING: /__w/xgboost/xgboost/src/collective/../data/../common/error_msg.h:83: If you are loading a serialized model (like pickle in Python, RDS in R) or
configuration generated by an older version of XGBoost, please export the model by calling
`Booster.save_model` from that version first, then load it back in current version. See:

    https://xgboost.readthedocs.io/en/stable/tutorials/saving_model.html

for more details about differences between saving model and serializing.

  setstate(state)

Model class       : XGBClassifier
Expected features : 2048
Booster features  : 2048
✓ Model loaded
✓ No prediction performed

----------------------------------------------------------------------
Target: BChE
Model : /content/drive/MyDrive/PhD_ML_Project/Models/XGBoost/BChE/BChE_XGBoost.pkl
Model class       : XGBClassifier
Expected features : 2048
Booster features  : 2048
✓ Model loaded
✓ No prediction performed

----------------------------------------------------------------------
Target: M2
Model : /content/drive/MyDrive/PhD_ML_Project/Models/XGBoost/M2/M2_XGBoost.pkl
Model class       : XGBClassifier
Expected features : 2048
Booster features  : 2048
✓ Model loaded
✓ No prediction performed

----------------------------------------------------------------------
Target: NMDAR
Model : /content/drive/MyDrive/PhD_ML_Project/Models/XGBoost/NMDAR/NMDAR_XGBoost.pkl
Model class       : XGBClassifier
Expected features : 2048
Booster features  : 2048
✓ Model loaded
✓ No prediction performed

----------------------------------------------------------------------
Target: 5HT6
Model : /content/drive/MyDrive/PhD_ML_Project/Models/XGBoost/5HT6/5HT6_XGBoost.pkl
Model class       : XGBClassifier
Expected features : 2048
Booster features  : 2048
✓ Model loaded
✓ No prediction performed

----------------------------------------------------------------------
Target: GSK3B
Model : /content/drive/MyDrive/PhD_ML_Project/Models/XGBoost/GSK3B/GSK3B_XGBoost.pkl
Model class       : XGBClassifier
Expected features : 2048
Booster features  : 2048
✓ Model loaded
✓ No prediction performed

----------------------------------------------------------------------
Target: MAOB
Model : /content/drive/MyDrive/PhD_ML_Project/Models/XGBoost/MAOB/MAOB_XGBoost.pkl
Model class       : XGBClassifier
Expected features : 2048
Booster features  : 2048
✓ Model loaded
✓ No prediction performed

----------------------------------------------------------------------
Target: PDE
Model : /content/drive/MyDrive/PhD_ML_Project/Models/XGBoost/PDE/PDE_XGBoost.pkl
Model class       : XGBClassifier
Expected features : 2048
Booster features  : 2048
✓ Model loaded
✓ No prediction performed

----------------------------------------------------------------------
Target: TNFA
Model : /content/drive/MyDrive/PhD_ML_Project/Models/XGBoost/TNFA/TNFA_XGBoost.pkl
Model class       : XGBClassifier
Expected features : 2048
Booster features  : 2048
✓ Model loaded
✓ No prediction performed

----------------------------------------------------------------------
Target: iNOS
Model : /content/drive/MyDrive/PhD_ML_Project/Models/XGBoost/iNOS/iNOS_XGBoost.pkl
Model class       : XGBClassifier
Expected features : 2048
Booster features  : 2048
✓ Model loaded
✓ No prediction performed

======================================================================
MODEL COMPATIBILITY SUMMARY
======================================================================
Models successfully loaded: 10
Expected fingerprint features: 2048
======================================================================

In [ ]:
# ============================================================
# VS-04 MEFSAT Batch 03 — CELL 10
# Frozen model prediction-interface QC
# ============================================================

print("=" * 70)
print("VS-04 MEFSAT BATCH 03 — MODEL INTERFACE QC")
print("=" * 70)

for target, model in frozen_models.items():

    print(f"\n{'-' * 70}")
    print(f"Target: {target}")

    # Model classes
    if hasattr(model, "classes_"):
        print(f"Classes           : {model.classes_}")
        print(f"Number of classes : {len(model.classes_)}")
    else:
        print("Classes           : attribute not available")

    # Confirm classifier interface exists
    print(
        f"predict()         : "
        f"{'available' if hasattr(model, 'predict') else 'NOT available'}"
    )

    print(
        f"predict_proba()   : "
        f"{'available' if hasattr(model, 'predict_proba') else 'NOT available'}"
    )

print("\n" + "=" * 70)
print("NO PREDICTIONS WERE PERFORMED")
print("=" * 70)

======================================================================
VS-04 MEFSAT BATCH 03 — MODEL INTERFACE QC
======================================================================

----------------------------------------------------------------------
Target: AChE
Classes           : [0 1]
Number of classes : 2
predict()         : available
predict_proba()   : available

----------------------------------------------------------------------
Target: BChE
Classes           : [0 1]
Number of classes : 2
predict()         : available
predict_proba()   : available

----------------------------------------------------------------------
Target: M2
Classes           : [0 1]
Number of classes : 2
predict()         : available
predict_proba()   : available

----------------------------------------------------------------------
Target: NMDAR
Classes           : [0 1]
Number of classes : 2
predict()         : available
predict_proba()   : available

----------------------------------------------------------------------
Target: 5HT6
Classes           : [0 1]
Number of classes : 2
predict()         : available
predict_proba()   : available

----------------------------------------------------------------------
Target: GSK3B
Classes           : [0 1]
Number of classes : 2
predict()         : available
predict_proba()   : available

----------------------------------------------------------------------
Target: MAOB
Classes           : [0 1]
Number of classes : 2
predict()         : available
predict_proba()   : available

----------------------------------------------------------------------
Target: PDE
Classes           : [0 1]
Number of classes : 2
predict()         : available
predict_proba()   : available

----------------------------------------------------------------------
Target: TNFA
Classes           : [0 1]
Number of classes : 2
predict()         : available
predict_proba()   : available

----------------------------------------------------------------------
Target: iNOS
Classes           : [0 1]
Number of classes : 2
predict()         : available
predict_proba()   : available

======================================================================
NO PREDICTIONS WERE PERFORMED
======================================================================

In [ ]:
# ============================================================
# VS-04 MEFSAT Batch 03 — CELL 11
# Controlled AChE prediction
# ============================================================

import numpy as np

print("=" * 70)
print("VS-04 MEFSAT BATCH 03 — AChE PREDICTION")
print("=" * 70)

# Retrieve the already-loaded frozen AChE model
ache_model = frozen_models["AChE"]

# ------------------------------------------------------------
# Perform prediction
# ------------------------------------------------------------

ache_pred = ache_model.predict(fingerprints)
ache_proba = ache_model.predict_proba(fingerprints)

# Extract probability for class 1
ache_prob_class1 = ache_proba[:, 1]

# ------------------------------------------------------------
# Basic output validation
# ------------------------------------------------------------

print(f"Number of compounds predicted : {len(ache_pred)}")
print(f"Prediction array shape         : {ache_pred.shape}")
print(f"Probability array shape        : {ache_proba.shape}")

print("\nPredicted classes:")
print(np.unique(ache_pred, return_counts=True))

print("\nClass 1 probability range:")
print(f"Minimum : {ache_prob_class1.min():.6f}")
print(f"Maximum : {ache_prob_class1.max():.6f}")
print(f"Mean    : {ache_prob_class1.mean():.6f}")

# ------------------------------------------------------------
# Create QC table — raw predictions only
# ------------------------------------------------------------

ache_qc = df[
    [
        "Serial_Number",
        "Secondary_Metabolite_Identifier",
        "Secondary_Metabolite_Name"
    ]
].copy()

ache_qc["AChE_Prediction"] = ache_pred
ache_qc["AChE_Probability_Class1"] = ache_prob_class1

print("\nFirst 10 AChE predictions:")
display(ache_qc.head(10))

print("=" * 70)
print("AChE prediction completed.")
print("No hit threshold applied.")
print("No compounds excluded.")
print("No ranking performed.")
print("=" * 70)

======================================================================
VS-04 MEFSAT BATCH 03 — AChE PREDICTION
======================================================================
Number of compounds predicted : 275
Prediction array shape         : (275,)
Probability array shape        : (275, 2)

Predicted classes:
(array([0]), array([275]))

Class 1 probability range:
Minimum : 0.000300
Maximum : 0.379748
Mean    : 0.030549

First 10 AChE predictions:

,Serial_Number,Secondary_Metabolite_Identifier,Secondary_Metabolite_Name,AChE_Prediction,AChE_Probability_Class1
0,48,MSID000048,(-)-Chizhine A,0,0.068991
1,49,MSID000049,(-)-Chizhine B,0,0.068991
2,50,MSID000050,(+)-Chizhine A,0,0.068991
3,51,MSID000051,(+)-Chizhine B,0,0.068991
4,52,MSID000052,(-)-Chizhine C,0,0.056838
5,53,MSID000053,(+)-Chizhine C,0,0.056838
6,56,MSID000056,(-)-Chizhine E,0,0.031745
7,57,MSID000057,(-)-Chizhine F,0,0.005421
8,71,MSID000071,(-)-Lingzhiol,0,0.138415
9,73,MSID000073,(+)-Lingzhiol,0,0.138415

======================================================================
AChE prediction completed.
No hit threshold applied.
No compounds excluded.
No ranking performed.
======================================================================

In [ ]:
# ============================================================
# VS-04 MEFSAT Batch 03 — CELL 12
# AChE probability distribution QC
# ============================================================

print("=" * 70)
print("VS-04 MEFSAT BATCH 03 — AChE PROBABILITY QC")
print("=" * 70)

# Sort raw AChE probabilities from highest to lowest
ache_probability_qc = ache_qc.sort_values(
    "AChE_Probability_Class1",
    ascending=False
).reset_index(drop=True)

# Display the top 20 compounds by raw class-1 probability
print("\nTop 20 compounds by AChE class-1 probability:")
display(
    ache_probability_qc[
        [
            "Serial_Number",
            "Secondary_Metabolite_Identifier",
            "Secondary_Metabolite_Name",
            "AChE_Prediction",
            "AChE_Probability_Class1"
        ]
    ].head(20)
)

# Probability summary
print("\nProbability summary:")
print(
    ache_qc["AChE_Probability_Class1"].describe(
        percentiles=[0.50, 0.75, 0.90, 0.95, 0.99]
    )
)

print("\nMaximum probability:")
max_idx = ache_qc["AChE_Probability_Class1"].idxmax()
print(
    ache_qc.loc[
        max_idx,
        [
            "Serial_Number",
            "Secondary_Metabolite_Identifier",
            "Secondary_Metabolite_Name",
            "AChE_Probability_Class1"
        ]
    ]
)

print("=" * 70)

======================================================================
VS-04 MEFSAT BATCH 03 — AChE PROBABILITY QC
======================================================================

Top 20 compounds by AChE class-1 probability:

,Serial_Number,Secondary_Metabolite_Identifier,Secondary_Metabolite_Name,AChE_Prediction,AChE_Probability_Class1
0,916,MSID000916,Ganodernoid D,0,0.379748
1,838,MSID000838,Ganoderic acid F,0,0.300998
2,1156,MSID001156,Lucidulactone A,0,0.292705
3,586,MSID000586,"12b-Hydroxy-3,7,11,15,23-pentaoxo-5 a -lanosta...",0,0.258261
4,146,MSID000146,12-Epi-ganoderlactone D,0,0.232445
5,968,MSID000968,Ganosporelactone A,0,0.230838
6,1759,MSID001759,"12b-Acetoxy-3,7,11,15,23-pentaoxolanost-8-en-2...",0,0.210255
7,1188,MSID001188,Methyl ganoderate F,0,0.194168
8,852,MSID000852,Ganoderic acid D1,0,0.187337
9,851,MSID000851,Ganoderic acid M,0,0.187337
10,1484,MSID001484,12-Acetoxy ganoderic acid D,0,0.174272
11,1740,MSID001740,"12b-Acetoxy-3,7,11,15,23-pentaoxo-5 a -lanosta...",0,0.172239
12,455,MSID000455,Butyl lucidenate D2,0,0.153536
13,1826,MSID001826,Lucidenic acid O,0,0.141034
14,71,MSID000071,(-)-Lingzhiol,0,0.138415
15,73,MSID000073,(+)-Lingzhiol,0,0.138415
16,1127,MSID001127,Lovastatin,0,0.127407
17,1192,MSID001192,Methyl lucidenate D 2,0,0.127116
18,1700,MSID001700,20-Hydroxylganoderic acid G,0,0.119944
19,1157,MSID001157,Lucidulactone B,0,0.117767

Probability summary:
count    275.000000
mean       0.030549
std        0.054050
min        0.000300
50%        0.009244
75%        0.032103
90%        0.074729
95%        0.139201
99%        0.267216
max        0.379748
Name: AChE_Probability_Class1, dtype: float64

Maximum probability:
Serial_Number                                916
Secondary_Metabolite_Identifier       MSID000916
Secondary_Metabolite_Name          Ganodernoid D
AChE_Probability_Class1                 0.379748
Name: 155, dtype: object
======================================================================

In [ ]:
# ============================================================
# VS-04 MEFSAT Batch 03 — CELL 13
# Create AChE raw prediction table
# ============================================================

ache_results = df.copy()

ache_results["AChE_Prediction"] = ache_pred
ache_results["AChE_Probability_Class1"] = ache_prob_class1

print("=" * 70)
print("VS-04 MEFSAT BATCH 03 — AChE RAW RESULTS")
print("=" * 70)

print(f"Rows                    : {len(ache_results)}")
print(f"AChE prediction column  : {'AChE_Prediction' in ache_results.columns}")
print(f"AChE probability column : {'AChE_Probability_Class1' in ache_results.columns}")

print("\nPrediction counts:")
print(ache_results["AChE_Prediction"].value_counts().sort_index())

print("\nMissing AChE predictions:")
print(ache_results["AChE_Prediction"].isna().sum())

print("\nMissing AChE probabilities:")
print(ache_results["AChE_Probability_Class1"].isna().sum())

print("\nAChE probability range:")
print(
    f"{ache_results['AChE_Probability_Class1'].min():.6f}"
    " to "
    f"{ache_results['AChE_Probability_Class1'].max():.6f}"
)

print("\nFirst 5 rows:")
display(
    ache_results[
        [
            "Secondary_Metabolite_Identifier",
            "Secondary_Metabolite_Name",
            "AChE_Prediction",
            "AChE_Probability_Class1"
        ]
    ].head()
)

print("=" * 70)
print("AChE raw result table created.")
print("No additional threshold applied.")
print("=" * 70)

======================================================================
VS-04 MEFSAT BATCH 03 — AChE RAW RESULTS
======================================================================
Rows                    : 275
AChE prediction column  : True
AChE probability column : True

Prediction counts:
AChE_Prediction
0    275
Name: count, dtype: int64

Missing AChE predictions:
0

Missing AChE probabilities:
0

AChE probability range:
0.000300 to 0.379748

First 5 rows:

,Secondary_Metabolite_Identifier,Secondary_Metabolite_Name,AChE_Prediction,AChE_Probability_Class1
0,MSID000048,(-)-Chizhine A,0,0.068991
1,MSID000049,(-)-Chizhine B,0,0.068991
2,MSID000050,(+)-Chizhine A,0,0.068991
3,MSID000051,(+)-Chizhine B,0,0.068991
4,MSID000052,(-)-Chizhine C,0,0.056838

======================================================================
AChE raw result table created.
No additional threshold applied.
======================================================================

In [ ]:
# ============================================================
# VS-04 MEFSAT Batch 03 — CELL 14
# One-shot prediction for remaining 9 frozen models
# ============================================================

print("=" * 70)
print("VS-04 MEFSAT BATCH 03 — MULTI-TARGET PREDICTION")
print("=" * 70)

# Remaining frozen targets
REMAINING_TARGETS = [
    "BChE",
    "M2",
    "NMDAR",
    "5HT6",
    "GSK3B",
    "MAOB",
    "PDE",
    "TNFA",
    "iNOS"
]

# Dictionary to store raw predictions
prediction_results = {}

for target in REMAINING_TARGETS:

    print(f"\n{'-' * 70}")
    print(f"Predicting: {target}")

    model = frozen_models[target]

    # Frozen model prediction
    predictions = model.predict(fingerprints)
    probabilities = model.predict_proba(fingerprints)

    # Class-1 probability
    probability_class1 = probabilities[:, 1]

    # Store raw outputs
    prediction_results[target] = {
        "prediction": predictions,
        "probability_class1": probability_class1
    }

    # Immediate integrity checks
    assert len(predictions) == 275
    assert probabilities.shape == (275, 2)
    assert len(probability_class1) == 275
    assert np.all(np.isfinite(probability_class1))

    print(f"Compounds predicted : {len(predictions)}")
    print(f"Probability shape   : {probabilities.shape}")

    unique_classes, class_counts = np.unique(
        predictions,
        return_counts=True
    )

    print("Prediction counts   :")
    for cls, count in zip(unique_classes, class_counts):
        print(f"  Class {cls}: {count}")

    print(
        f"Class-1 probability : "
        f"{probability_class1.min():.6f} - "
        f"{probability_class1.max():.6f}"
    )

print("\n" + "=" * 70)
print("MULTI-TARGET PREDICTION SUMMARY")
print("=" * 70)

print(f"Targets processed : {len(prediction_results)}")

for target in REMAINING_TARGETS:
    pred = prediction_results[target]["prediction"]
    prob = prediction_results[target]["probability_class1"]

    print(
        f"{target:7s} | "
        f"n={len(pred):3d} | "
        f"class-1={np.sum(pred == 1):3d} | "
        f"class-0={np.sum(pred == 0):3d} | "
        f"max P(1)={prob.max():.6f}"
    )

print("=" * 70)
print("All 9 remaining frozen models predicted.")
print("No hit threshold applied.")
print("No compounds excluded.")
print("No ranking performed.")
print("=" * 70)

======================================================================
VS-04 MEFSAT BATCH 03 — MULTI-TARGET PREDICTION
======================================================================

----------------------------------------------------------------------
Predicting: BChE
Compounds predicted : 275
Probability shape   : (275, 2)
Prediction counts   :
  Class 0: 275
Class-1 probability : 0.000072 - 0.396515

----------------------------------------------------------------------
Predicting: M2
Compounds predicted : 275
Probability shape   : (275, 2)
Prediction counts   :
  Class 0: 275
Class-1 probability : 0.000990 - 0.138093

----------------------------------------------------------------------
Predicting: NMDAR
Compounds predicted : 275
Probability shape   : (275, 2)
Prediction counts   :
  Class 0: 275
Class-1 probability : 0.000116 - 0.028208

----------------------------------------------------------------------
Predicting: 5HT6
Compounds predicted : 275
Probability shape   : (275, 2)
Prediction counts   :
  Class 0: 275
Class-1 probability : 0.000990 - 0.138093

----------------------------------------------------------------------
Predicting: GSK3B
Compounds predicted : 275
Probability shape   : (275, 2)
Prediction counts   :
  Class 0: 275
Class-1 probability : 0.000119 - 0.297238

----------------------------------------------------------------------
Predicting: MAOB
Compounds predicted : 275
Probability shape   : (275, 2)
Prediction counts   :
  Class 0: 273
  Class 1: 2
Class-1 probability : 0.000035 - 0.603247

----------------------------------------------------------------------
Predicting: PDE
Compounds predicted : 275
Probability shape   : (275, 2)
Prediction counts   :
  Class 0: 275
Class-1 probability : 0.000254 - 0.139015

----------------------------------------------------------------------
Predicting: TNFA
Compounds predicted : 275
Probability shape   : (275, 2)
Prediction counts   :
  Class 0: 275
Class-1 probability : 0.000998 - 0.163686

----------------------------------------------------------------------
Predicting: iNOS
Compounds predicted : 275
Probability shape   : (275, 2)
Prediction counts   :
  Class 0: 275
Class-1 probability : 0.001946 - 0.498271

======================================================================
MULTI-TARGET PREDICTION SUMMARY
======================================================================
Targets processed : 9
BChE    | n=275 | class-1=  0 | class-0=275 | max P(1)=0.396515
M2      | n=275 | class-1=  0 | class-0=275 | max P(1)=0.138093
NMDAR   | n=275 | class-1=  0 | class-0=275 | max P(1)=0.028208
5HT6    | n=275 | class-1=  0 | class-0=275 | max P(1)=0.138093
GSK3B   | n=275 | class-1=  0 | class-0=275 | max P(1)=0.297238
MAOB    | n=275 | class-1=  2 | class-0=273 | max P(1)=0.603247
PDE     | n=275 | class-1=  0 | class-0=275 | max P(1)=0.139015
TNFA    | n=275 | class-1=  0 | class-0=275 | max P(1)=0.163686
iNOS    | n=275 | class-1=  0 | class-0=275 | max P(1)=0.498271
======================================================================
All 9 remaining frozen models predicted.
No hit threshold applied.
No compounds excluded.
No ranking performed.
======================================================================

In [ ]:
# ============================================================
# VS-04 MEFSAT Batch 03 — CELL 15
# Build master raw prediction table
# ============================================================

print("=" * 70)
print("VS-04 MEFSAT BATCH 03 — MASTER RAW PREDICTION TABLE")
print("=" * 70)

# Start from the original validated 275-compound library
master_predictions = df.copy()

# ------------------------------------------------------------
# Add AChE results
# ------------------------------------------------------------

master_predictions["AChE_Prediction"] = ache_pred
master_predictions["AChE_Probability_Class1"] = ache_prob_class1

# ------------------------------------------------------------
# Add the remaining 9 target results
# ------------------------------------------------------------

for target in REMAINING_TARGETS:

    master_predictions[f"{target}_Prediction"] = (
        prediction_results[target]["prediction"]
    )

    master_predictions[f"{target}_Probability_Class1"] = (
        prediction_results[target]["probability_class1"]
    )

# ------------------------------------------------------------
# Master-table integrity checks
# ------------------------------------------------------------

print(f"Rows                    : {len(master_predictions)}")

expected_prediction_columns = [
    f"{target}_Prediction"
    for target in TARGETS
]

expected_probability_columns = [
    f"{target}_Probability_Class1"
    for target in TARGETS
]

missing_prediction_columns = [
    col for col in expected_prediction_columns
    if col not in master_predictions.columns
]

missing_probability_columns = [
    col for col in expected_probability_columns
    if col not in master_predictions.columns
]

print(f"Prediction columns      : {len(expected_prediction_columns)}")
print(f"Probability columns     : {len(expected_probability_columns)}")

print("\nMissing prediction columns:")
print(missing_prediction_columns)

print("\nMissing probability columns:")
print(missing_probability_columns)

# Check every target has 275 predictions and 275 probabilities
print("\nTarget-level row checks:")

for target in TARGETS:

    pred_col = f"{target}_Prediction"
    prob_col = f"{target}_Probability_Class1"

    assert master_predictions[pred_col].notna().all()
    assert master_predictions[prob_col].notna().all()
    assert len(master_predictions[pred_col]) == 275
    assert len(master_predictions[prob_col]) == 275

    print(
        f"✓ {target:7s} | "
        f"predictions={master_predictions[pred_col].notna().sum():3d} | "
        f"probabilities={master_predictions[prob_col].notna().sum():3d}"
    )

print("\nFirst 5 rows of prediction columns:")

display(
    master_predictions[
        ["Secondary_Metabolite_Identifier"] +
        expected_prediction_columns +
        expected_probability_columns
    ].head()
)

print("=" * 70)
print("MASTER RAW PREDICTION TABLE CREATED")
print("No hit threshold applied.")
print("No compounds excluded.")
print("No ranking performed.")
print("=" * 70)

======================================================================
VS-04 MEFSAT BATCH 03 — MASTER RAW PREDICTION TABLE
======================================================================
Rows                    : 275
Prediction columns      : 10
Probability columns     : 10

Missing prediction columns:
[]

Missing probability columns:
[]

Target-level row checks:
✓ AChE    | predictions=275 | probabilities=275
✓ BChE    | predictions=275 | probabilities=275
✓ M2      | predictions=275 | probabilities=275
✓ NMDAR   | predictions=275 | probabilities=275
✓ 5HT6    | predictions=275 | probabilities=275
✓ GSK3B   | predictions=275 | probabilities=275
✓ MAOB    | predictions=275 | probabilities=275
✓ PDE     | predictions=275 | probabilities=275
✓ TNFA    | predictions=275 | probabilities=275
✓ iNOS    | predictions=275 | probabilities=275

First 5 rows of prediction columns:

,Secondary_Metabolite_Identifier,AChE_Prediction,BChE_Prediction,M2_Prediction,NMDAR_Prediction,5HT6_Prediction,GSK3B_Prediction,MAOB_Prediction,PDE_Prediction,TNFA_Prediction,...,AChE_Probability_Class1,BChE_Probability_Class1,M2_Probability_Class1,NMDAR_Probability_Class1,5HT6_Probability_Class1,GSK3B_Probability_Class1,MAOB_Probability_Class1,PDE_Probability_Class1,TNFA_Probability_Class1,iNOS_Probability_Class1
0,MSID000048,0,0,0,0,0,0,0,0,0,...,0.068991,0.084591,0.004286,0.003324,0.004286,0.004592,0.011686,0.000254,0.016609,0.011100
1,MSID000049,0,0,0,0,0,0,0,0,0,...,0.068991,0.084591,0.004286,0.003324,0.004286,0.004592,0.011686,0.000254,0.016609,0.011100
2,MSID000050,0,0,0,0,0,0,0,0,0,...,0.068991,0.084591,0.004286,0.003324,0.004286,0.004592,0.011686,0.000254,0.016609,0.011100
3,MSID000051,0,0,0,0,0,0,0,0,0,...,0.068991,0.084591,0.004286,0.003324,0.004286,0.004592,0.011686,0.000254,0.016609,0.011100
4,MSID000052,0,0,0,0,0,0,0,0,0,...,0.056838,0.011463,0.006274,0.004409,0.006274,0.005192,0.000488,0.001032,0.006257,0.014467

======================================================================
MASTER RAW PREDICTION TABLE CREATED
No hit threshold applied.
No compounds excluded.
No ranking performed.
======================================================================

In [ ]:
# ============================================================
# VS-04 MEFSAT Batch 03 — CELL 16
# Inspect existing screening-decision fields
# ============================================================

print("=" * 70)
print("VS-04 MEFSAT BATCH 03 — SCREENING DECISION QC")
print("=" * 70)

print("\nExisting Screening_Decision values:")
print(
    master_predictions["Screening_Decision"]
    .value_counts(dropna=False)
)

print("\nExisting Structural_QC values:")
print(
    master_predictions["Structural_QC"]
    .value_counts(dropna=False)
)

print("\nExisting Exclusion_Reason values:")
print(
    master_predictions["Exclusion_Reason"]
    .value_counts(dropna=False)
)

print("\nDecision-related columns:")
decision_columns = [
    col for col in master_predictions.columns
    if any(term in col.lower() for term in [
        "decision",
        "exclude",
        "hold",
        "screen",
        "qc"
    ])
]

for col in decision_columns:
    print(f" - {col}")

print("=" * 70)

======================================================================
VS-04 MEFSAT BATCH 03 — SCREENING DECISION QC
======================================================================

Existing Screening_Decision values:
Screening_Decision
Include    275
Name: count, dtype: int64

Existing Structural_QC values:
Structural_QC
Valid    275
Name: count, dtype: int64

Existing Exclusion_Reason values:
Exclusion_Reason
NaN    275
Name: count, dtype: int64

Decision-related columns:
 - Screening_Decision
 - Structural_QC
======================================================================

In [ ]:
# ============================================================
# VS-04 MEFSAT Batch 03 — CELL 17
# Extract predicted receptor hits
# ============================================================

print("=" * 70)
print("VS-04 MEFSAT BATCH 03 — PREDICTED HIT EXTRACTION")
print("=" * 70)

# Receptor-level prediction columns
prediction_columns = {
    "AChE": "AChE_Prediction",
    "BChE": "BChE_Prediction",
    "M2": "M2_Prediction",
    "NMDAR": "NMDAR_Prediction",
    "5HT6": "5HT6_Prediction",
    "GSK3B": "GSK3B_Prediction",
    "MAOB": "MAOB_Prediction",
    "PDE": "PDE_Prediction",
    "TNFA": "TNFA_Prediction",
    "iNOS": "iNOS_Prediction"
}

probability_columns = {
    "AChE": "AChE_Probability_Class1",
    "BChE": "BChE_Probability_Class1",
    "M2": "M2_Probability_Class1",
    "NMDAR": "NMDAR_Probability_Class1",
    "5HT6": "5HT6_Probability_Class1",
    "GSK3B": "GSK3B_Probability_Class1",
    "MAOB": "MAOB_Probability_Class1",
    "PDE": "PDE_Probability_Class1",
    "TNFA": "TNFA_Probability_Class1",
    "iNOS": "iNOS_Probability_Class1"
}

hit_tables = []

for target in TARGETS:

    pred_col = prediction_columns[target]
    prob_col = probability_columns[target]

    # Select compounds predicted as class 1
    target_hits = master_predictions[
        master_predictions[pred_col] == 1
    ].copy()

    # Keep relevant information
    target_hits = target_hits[
        [
            "Serial_Number",
            "Secondary_Metabolite_Identifier",
            "Secondary_Metabolite_Name",
            "SMILES",
            "Canonical_SMILES",
            pred_col,
            prob_col
        ]
    ].copy()

    # Standardise output column names
    target_hits = target_hits.rename(
        columns={
            pred_col: "Predicted_Class",
            prob_col: "Active_Probability"
        }
    )

    # Add receptor
    target_hits.insert(
        5,
        "Target",
        target
    )

    hit_tables.append(target_hits)

# Combine all receptor-level hits
if hit_tables:
    hit_table = pd.concat(
        hit_tables,
        ignore_index=True
    )
else:
    hit_table = pd.DataFrame()

print("\nPredicted hits by target:")
print(
    master_predictions[
        list(prediction_columns.values())
    ].sum()
)

print("\nTotal predicted hit rows:")
print(len(hit_table))

print("\nHit table:")
if len(hit_table) > 0:
    display(hit_table)
else:
    print("No predicted hits identified.")

print("=" * 70)
print("No probability threshold applied.")
print("Hit criterion: Predicted_Class == 1")
print("=" * 70)

======================================================================
VS-04 MEFSAT BATCH 03 — PREDICTED HIT EXTRACTION
======================================================================

Predicted hits by target:
AChE_Prediction     0
BChE_Prediction     0
M2_Prediction       0
NMDAR_Prediction    0
5HT6_Prediction     0
GSK3B_Prediction    0
MAOB_Prediction     2
PDE_Prediction      0
TNFA_Prediction     0
iNOS_Prediction     0
dtype: int64

Total predicted hit rows:
2

Hit table:

,Serial_Number,Secondary_Metabolite_Identifier,Secondary_Metabolite_Name,SMILES,Canonical_SMILES,Target,Predicted_Class,Active_Probability
0,922,MSID000922,Ganodone,CC(=O)c1ccc(cc1O)OC1Cc2c(O1)ccc(c2O)C(=O)C,CC(=O)c1ccc(OC2Cc3c(ccc(C(C)=O)c3O)O2)cc1O,MAOB,1,0.541586
1,1152,MSID001152,Lucidimine B,Oc1ccc2c(c1)c1ncc3c(c1CO2)CCC3,Oc1ccc2c(c1)-c1ncc3c(c1CO2)CCC3,MAOB,1,0.603247

======================================================================
No probability threshold applied.
Hit criterion: Predicted_Class == 1
======================================================================

In [ ]:
# ============================================================
# VS-04 MEFSAT Batch 03 — CELL 18
# Final predicted-hit QC
# ============================================================

print("=" * 70)
print("VS-04 MEFSAT BATCH 03 — FINAL HIT QC")
print("=" * 70)

# Expected number of predicted hits
print(f"Total predicted hit rows : {len(hit_table)}")

# Essential fields
essential_columns = [
    "Secondary_Metabolite_Identifier",
    "Secondary_Metabolite_Name",
    "SMILES",
    "Canonical_SMILES",
    "Target",
    "Predicted_Class",
    "Active_Probability"
]

print("\nMissing essential values:")
print(hit_table[essential_columns].isna().sum())

# Duplicate checks
print("\nDuplicate compound-target rows:")
print(
    hit_table.duplicated(
        subset=[
            "Secondary_Metabolite_Identifier",
            "Target"
        ]
    ).sum()
)

print("\nUnique compounds among hits:")
print(
    hit_table["Secondary_Metabolite_Identifier"].nunique()
)

print("\nUnique targets among hits:")
print(
    hit_table["Target"].nunique()
)

print("\nPredicted class values:")
print(
    hit_table["Predicted_Class"].value_counts(dropna=False)
)

print("\nFinal hit table:")
display(hit_table)

print("=" * 70)
print("FINAL HIT QC COMPLETE")
print("=" * 70)

======================================================================
VS-04 MEFSAT BATCH 03 — FINAL HIT QC
======================================================================
Total predicted hit rows : 2

Missing essential values:
Secondary_Metabolite_Identifier    0
Secondary_Metabolite_Name          0
SMILES                             0
Canonical_SMILES                   0
Target                             0
Predicted_Class                    0
Active_Probability                 0
dtype: int64

Duplicate compound-target rows:
0

Unique compounds among hits:
2

Unique targets among hits:
1

Predicted class values:
Predicted_Class
1    2
Name: count, dtype: int64

Final hit table:

,Serial_Number,Secondary_Metabolite_Identifier,Secondary_Metabolite_Name,SMILES,Canonical_SMILES,Target,Predicted_Class,Active_Probability
0,922,MSID000922,Ganodone,CC(=O)c1ccc(cc1O)OC1Cc2c(O1)ccc(c2O)C(=O)C,CC(=O)c1ccc(OC2Cc3c(ccc(C(C)=O)c3O)O2)cc1O,MAOB,1,0.541586
1,1152,MSID001152,Lucidimine B,Oc1ccc2c(c1)c1ncc3c(c1CO2)CCC3,Oc1ccc2c(c1)-c1ncc3c(c1CO2)CCC3,MAOB,1,0.603247

======================================================================
FINAL HIT QC COMPLETE
======================================================================

In [ ]:
# ============================================================
# VS-04 MEFSAT Batch 03 — CELL 18
# Final predicted-hit QC
# ============================================================

print("=" * 70)
print("VS-04 MEFSAT BATCH 03 — FINAL PREDICTED-HIT QC")
print("=" * 70)

essential_columns = [
    "Secondary_Metabolite_Identifier",
    "Secondary_Metabolite_Name",
    "SMILES",
    "Canonical_SMILES",
    "Target",
    "Predicted_Class",
    "Active_Probability"
]

print(f"Total predicted hit rows : {len(hit_table)}")

print("\nMissing essential values:")
print(hit_table[essential_columns].isna().sum())

print("\nDuplicate compound-target rows:")
print(
    hit_table.duplicated(
        subset=[
            "Secondary_Metabolite_Identifier",
            "Target"
        ]
    ).sum()
)

print("\nUnique compounds among hits:")
print(
    hit_table["Secondary_Metabolite_Identifier"].nunique()
)

print("\nUnique targets among hits:")
print(
    hit_table["Target"].nunique()
)

print("\nPredicted class values:")
print(
    hit_table["Predicted_Class"].value_counts(dropna=False)
)

print("\nFinal predicted-hit table:")
display(hit_table)

print("=" * 70)
print("FINAL PREDICTED-HIT QC COMPLETE")
print("=" * 70)

======================================================================
VS-04 MEFSAT BATCH 03 — FINAL PREDICTED-HIT QC
======================================================================
Total predicted hit rows : 2

Missing essential values:
Secondary_Metabolite_Identifier    0
Secondary_Metabolite_Name          0
SMILES                             0
Canonical_SMILES                   0
Target                             0
Predicted_Class                    0
Active_Probability                 0
dtype: int64

Duplicate compound-target rows:
0

Unique compounds among hits:
2

Unique targets among hits:
1

Predicted class values:
Predicted_Class
1    2
Name: count, dtype: int64

Final predicted-hit table:

,Serial_Number,Secondary_Metabolite_Identifier,Secondary_Metabolite_Name,SMILES,Canonical_SMILES,Target,Predicted_Class,Active_Probability
0,922,MSID000922,Ganodone,CC(=O)c1ccc(cc1O)OC1Cc2c(O1)ccc(c2O)C(=O)C,CC(=O)c1ccc(OC2Cc3c(ccc(C(C)=O)c3O)O2)cc1O,MAOB,1,0.541586
1,1152,MSID001152,Lucidimine B,Oc1ccc2c(c1)c1ncc3c(c1CO2)CCC3,Oc1ccc2c(c1)-c1ncc3c(c1CO2)CCC3,MAOB,1,0.603247

======================================================================
FINAL PREDICTED-HIT QC COMPLETE
======================================================================

In [ ]:
# ============================================================
# VS-04 MEFSAT Batch 03 — CELL 19
# Save final prediction outputs
# ============================================================

import os

OUTPUT_DIR = (
    "/content/drive/MyDrive/PhD_ML_Project/"
    "VS-04_Batch_03_MEFSAT/03_Prediction"
)

os.makedirs(OUTPUT_DIR, exist_ok=True)

# ------------------------------------------------------------
# Output paths
# ------------------------------------------------------------

MASTER_OUTPUT = os.path.join(
    OUTPUT_DIR,
    "Batch03_MEFSAT_Glucidum_Master_Predictions.csv"
)

HITS_OUTPUT = os.path.join(
    OUTPUT_DIR,
    "Batch03_MEFSAT_Glucidum_Predicted_Hits.csv"
)

# ------------------------------------------------------------
# Save complete 275-compound prediction table
# ------------------------------------------------------------

master_predictions.to_csv(
    MASTER_OUTPUT,
    index=False
)

# ------------------------------------------------------------
# Save predicted-hit table
# ------------------------------------------------------------

hit_table.to_csv(
    HITS_OUTPUT,
    index=False
)

# ------------------------------------------------------------
# Verify files
# ------------------------------------------------------------

print("=" * 70)
print("VS-04 MEFSAT BATCH 03 — OUTPUT FILES")
print("=" * 70)

print(f"\nMaster prediction file:")
print(MASTER_OUTPUT)

print(f"\nPredicted-hit file:")
print(HITS_OUTPUT)

print("\nFile existence check:")
print(
    f"Master predictions : "
    f"{os.path.exists(MASTER_OUTPUT)}"
)

print(
    f"Predicted hits     : "
    f"{os.path.exists(HITS_OUTPUT)}"
)

print("\nRow counts:")
print(
    f"Master predictions : "
    f"{len(pd.read_csv(MASTER_OUTPUT))}"
)

print(
    f"Predicted hits     : "
    f"{len(pd.read_csv(HITS_OUTPUT))}"
)

print("=" * 70)
print("BATCH 03 PREDICTION OUTPUTS SAVED")
print("=" * 70)

======================================================================
VS-04 MEFSAT BATCH 03 — OUTPUT FILES
======================================================================

Master prediction file:
/content/drive/MyDrive/PhD_ML_Project/VS-04_Batch_03_MEFSAT/03_Prediction/Batch03_MEFSAT_Glucidum_Master_Predictions.csv

Predicted-hit file:
/content/drive/MyDrive/PhD_ML_Project/VS-04_Batch_03_MEFSAT/03_Prediction/Batch03_MEFSAT_Glucidum_Predicted_Hits.csv

File existence check:
Master predictions : True
Predicted hits     : True

Row counts:
Master predictions : 275
Predicted hits     : 2
======================================================================
BATCH 03 PREDICTION OUTPUTS SAVED
======================================================================

In [ ]:
# ============================================================
# VS-04 MEFSAT Batch 03 — CELL 20
# Final saved-file verification
# ============================================================

print("=" * 70)
print("VS-04 MEFSAT BATCH 03 — FINAL FILE VERIFICATION")
print("=" * 70)

# Reload saved files
master_check = pd.read_csv(MASTER_OUTPUT)
hits_check = pd.read_csv(HITS_OUTPUT)

# ------------------------------------------------------------
# Master prediction file checks
# ------------------------------------------------------------

print("\nMASTER PREDICTION FILE")
print("-" * 70)

print(f"Rows    : {len(master_check)}")
print(f"Columns : {len(master_check.columns)}")

print("\nPrediction counts from saved file:")

for target in TARGETS:
    col = f"{target}_Prediction"

    class_counts = master_check[col].value_counts().sort_index()

    print(f"\n{target}:")
    print(class_counts.to_dict())

# ------------------------------------------------------------
# Predicted-hit file checks
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PREDICTED-HIT FILE")
print("=" * 70)

print(f"Rows    : {len(hits_check)}")
print(f"Columns : {len(hits_check.columns)}")

print("\nSaved predicted hits:")
display(hits_check)

print("\nTarget distribution:")
print(hits_check["Target"].value_counts())

print("\nPredicted class distribution:")
print(hits_check["Predicted_Class"].value_counts())

print("\nMissing essential values:")
print(
    hits_check[
        [
            "Secondary_Metabolite_Identifier",
            "Secondary_Metabolite_Name",
            "SMILES",
            "Canonical_SMILES",
            "Target",
            "Predicted_Class",
            "Active_Probability"
        ]
    ].isna().sum()
)

print("=" * 70)
print("FINAL SAVED-FILE VERIFICATION COMPLETE")
print("=" * 70)

======================================================================
VS-04 MEFSAT BATCH 03 — FINAL FILE VERIFICATION
======================================================================

MASTER PREDICTION FILE
----------------------------------------------------------------------
Rows    : 275
Columns : 91

Prediction counts from saved file:

AChE:
{0: 275}

BChE:
{0: 275}

M2:
{0: 275}

NMDAR:
{0: 275}

5HT6:
{0: 275}

GSK3B:
{0: 275}

MAOB:
{0: 273, 1: 2}

PDE:
{0: 275}

TNFA:
{0: 275}

iNOS:
{0: 275}

======================================================================
PREDICTED-HIT FILE
======================================================================
Rows    : 2
Columns : 8

Saved predicted hits:

,Serial_Number,Secondary_Metabolite_Identifier,Secondary_Metabolite_Name,SMILES,Canonical_SMILES,Target,Predicted_Class,Active_Probability
0,922,MSID000922,Ganodone,CC(=O)c1ccc(cc1O)OC1Cc2c(O1)ccc(c2O)C(=O)C,CC(=O)c1ccc(OC2Cc3c(ccc(C(C)=O)c3O)O2)cc1O,MAOB,1,0.541586
1,1152,MSID001152,Lucidimine B,Oc1ccc2c(c1)c1ncc3c(c1CO2)CCC3,Oc1ccc2c(c1)-c1ncc3c(c1CO2)CCC3,MAOB,1,0.603247

Target distribution:
Target
MAOB    2
Name: count, dtype: int64

Predicted class distribution:
Predicted_Class
1    2
Name: count, dtype: int64

Missing essential values:
Secondary_Metabolite_Identifier    0
Secondary_Metabolite_Name          0
SMILES                             0
Canonical_SMILES                   0
Target                             0
Predicted_Class                    0
Active_Probability                 0
dtype: int64
======================================================================
FINAL SAVED-FILE VERIFICATION COMPLETE
======================================================================

In [ ]:
# ============================================================
# VS-04 — DEFINE TABLE 2
# ============================================================

import pandas as pd

TABLE2_PATH = (
    "/content/drive/MyDrive/PhD_ML_Project/VS04_Screening/"
    "Batch_02_Table2/01_Raw/Table2_Raw_32_compounds.csv"
)

table2 = pd.read_csv(TABLE2_PATH)

print("=" * 70)
print("TABLE 2 LOADED")
print("=" * 70)

print("\nTable 2 shape:", table2.shape)

print("\nTable 2 columns:")
print(table2.columns.tolist())

display(table2.head())

print("=" * 70)
print("✓ TABLE 2 READY")
print("=" * 70)

======================================================================
TABLE 2 LOADED
======================================================================

Table 2 shape: (32, 3)

Table 2 columns:
['Table2_ID', 'Compound_Name_Paper', 'Source']

  Table2_ID Compound_Name_Paper                        Source
0     T2_01  Ganolucidic acid A  Cheng et al. (2021), Table 2
1     T2_02    Ganoderic acid A  Cheng et al. (2021), Table 2
2     T2_03  Ganolucidic acid D  Cheng et al. (2021), Table 2
3     T2_04    Ganoderic acid B  Cheng et al. (2021), Table 2
4     T2_05    Ganoderic acid E  Cheng et al. (2021), Table 2

======================================================================
✓ TABLE 2 READY
======================================================================

In [ ]:
# ============================================================
# VS-04 — CELL 21A
# Validate Table 2 ↔ MEFSAT exact compound-name matches
# ============================================================

print("=" * 70)
print("VS-04 — TABLE 2 ↔ MEFSAT EXACT MATCH VALIDATION")
print("=" * 70)

# ------------------------------------------------------------
# Create normalised names
# ------------------------------------------------------------

table2_names = (
    table2["Verified_Name"]
    .astype(str)
    .str.strip()
    .str.lower()
)

mefsat_names = (
    mefsat["Secondary_Metabolite_Name"]
    .astype(str)
    .str.strip()
    .str.lower()
)

# ------------------------------------------------------------
# Find exact overlaps
# ------------------------------------------------------------

overlap_names = sorted(
    set(table2_names) & set(mefsat_names)
)

print(f"\nExact name matches: {len(overlap_names)}")

# ------------------------------------------------------------
# Build mapping table WITHOUT merge()
# ------------------------------------------------------------

matched_rows = []

for name in overlap_names:

    table2_match = table2.loc[
        table2_names == name
    ].iloc[0]

    mefsat_match = mefsat.loc[
        mefsat_names == name
    ].iloc[0]

    matched_rows.append({
        "Table2_ID": table2_match["Table2_ID"],
        "Table2_Name": table2_match["Verified_Name"],
        "MEFSAT_MSID": mefsat_match[
            "Secondary_Metabolite_Identifier"
        ],
        "MEFSAT_Name": mefsat_match[
            "Secondary_Metabolite_Name"
        ]
    })

overlap_table = pd.DataFrame(matched_rows)

# ------------------------------------------------------------
# Display mapping
# ------------------------------------------------------------

print("\nMatched compounds:")
display(overlap_table)

# ------------------------------------------------------------
# Integrity checks
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("MATCH INTEGRITY CHECKS")
print("=" * 70)

print(
    "Unique Table 2 IDs matched :",
    overlap_table["Table2_ID"].nunique()
)

print(
    "Unique MEFSAT MSIDs matched:",
    overlap_table["MEFSAT_MSID"].nunique()
)

print(
    "Duplicate Table 2 IDs      :",
    overlap_table["Table2_ID"].duplicated().sum()
)

print(
    "Duplicate MEFSAT MSIDs     :",
    overlap_table["MEFSAT_MSID"].duplicated().sum()
)

print("=" * 70)
print("NO DATA MERGED")
print("NO ORIGINAL DATA MODIFIED")
print("=" * 70)

======================================================================
VS-04 — TABLE 2 ↔ MEFSAT EXACT MATCH VALIDATION
======================================================================

KeyError: 'Verified_Name'

In [ ]:
# ============================================================
# VS-04 — CELL 22
# Compare prediction classes for 15 overlapping compounds
# ============================================================

print("=" * 70)
print("VS-04 — OVERLAPPING COMPOUNDS: PREDICTION CLASS COMPARISON")
print("=" * 70)

# ------------------------------------------------------------
# Define the 10 targets
# ------------------------------------------------------------

TARGETS = [
    "AChE",
    "BChE",
    "M2",
    "NMDAR",
    "5HT6",
    "GSK3B",
    "MAOB",
    "PDE",
    "TNFA",
    "iNOS"
]

# ------------------------------------------------------------
# Identify Table 2 prediction columns
# ------------------------------------------------------------

table2_prediction_columns = {
    target: f"{target}_Prediction"
    for target in TARGETS
}

# Verify columns exist
missing_table2 = [
    col for col in table2_prediction_columns.values()
    if col not in table2.columns
]

print("\nMissing Table 2 prediction columns:")
print(missing_table2)

# ------------------------------------------------------------
# Create comparison table using validated mapping
# ------------------------------------------------------------

comparison_class = overlap_table[
    [
        "Table2_ID",
        "Table2_Name",
        "MEFSAT_MSID",
        "MEFSAT_Name"
    ]
].copy()

# ------------------------------------------------------------
# Add prediction classes from both datasets
# ------------------------------------------------------------

for target in TARGETS:

    table2_id = comparison_class["Table2_ID"]

    # Table 2 predictions
    table2_lookup = (
        table2[
            ["Table2_ID", table2_prediction_columns[target]]
        ]
        .drop_duplicates("Table2_ID")
        .set_index("Table2_ID")
    )

    comparison_class[f"{target}_Table2"] = (
        table2_id.map(
            table2_lookup[
                table2_prediction_columns[target]
            ]
        )
    )

    # MEFSAT predictions
    mefsat_lookup = (
        mefsat[
            [
                "Secondary_Metabolite_Identifier",
                f"{target}_Prediction"
            ]
        ]
        .drop_duplicates(
            "Secondary_Metabolite_Identifier"
        )
        .set_index(
            "Secondary_Metabolite_Identifier"
        )
    )

    comparison_class[f"{target}_MEFSAT"] = (
        comparison_class["MEFSAT_MSID"].map(
            mefsat_lookup[f"{target}_Prediction"]
        )
    )

# ------------------------------------------------------------
# QC: no missing predictions
# ------------------------------------------------------------

prediction_columns = [
    col for col in comparison_class.columns
    if col.endswith("_Table2") or col.endswith("_MEFSAT")
]

print("\nMissing prediction values:")
print(
    comparison_class[prediction_columns].isna().sum()
)

# ------------------------------------------------------------
# Calculate agreement for each compound
# ------------------------------------------------------------

agreement_counts = []

for _, row in comparison_class.iterrows():

    agreements = 0

    for target in TARGETS:

        t2 = row[f"{target}_Table2"]
        mf = row[f"{target}_MEFSAT"]

        if t2 == mf:
            agreements += 1

    agreement_counts.append(agreements)

comparison_class["Number_of_Targets_Agreeing"] = (
    agreement_counts
)

comparison_class["Number_of_Targets_Differing"] = (
    len(TARGETS) -
    comparison_class["Number_of_Targets_Agreeing"]
)

# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PREDICTION CLASS COMPARISON")
print("=" * 70)

display(comparison_class)

# ------------------------------------------------------------
# Overall agreement summary
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("AGREEMENT SUMMARY")
print("=" * 70)

print(
    f"Overlapping compounds : {len(comparison_class)}"
)

print(
    f"Targets compared      : {len(TARGETS)}"
)

print(
    f"Total comparisons     : "
    f"{len(comparison_class) * len(TARGETS)}"
)

total_agreements = (
    comparison_class["Number_of_Targets_Agreeing"]
    .sum()
)

total_differences = (
    comparison_class["Number_of_Targets_Differing"]
    .sum()
)

print(f"Agreements             : {total_agreements}")
print(f"Differences            : {total_differences}")

print("\nAgreement per compound:")
display(
    comparison_class[
        [
            "Table2_ID",
            "Table2_Name",
            "MEFSAT_MSID",
            "Number_of_Targets_Agreeing",
            "Number_of_Targets_Differing"
        ]
    ]
)

print("=" * 70)
print("NO SOURCE DATA MODIFIED")
print("=" * 70)

In [ ]:
# ============================================================
# VS-04 — CELL 23
# Compare active probabilities for 15 overlapping compounds
# ============================================================

print("=" * 70)
print("VS-04 — OVERLAPPING COMPOUNDS: PROBABILITY COMPARISON")
print("=" * 70)

# ------------------------------------------------------------
# Identify probability columns
# ------------------------------------------------------------

table2_probability_columns = {
    target: f"{target}_Probability"
    for target in TARGETS
}

mefsat_probability_columns = {
    target: f"{target}_Probability_Class1"
    for target in TARGETS
}

# Check Table 2 columns
missing_table2_probability = [
    col
    for col in table2_probability_columns.values()
    if col not in table2.columns
]

# Check MEFSAT columns
missing_mefsat_probability = [
    col
    for col in mefsat_probability_columns.values()
    if col not in mefsat.columns
]

print("\nMissing Table 2 probability columns:")
print(missing_table2_probability)

print("\nMissing MEFSAT probability columns:")
print(missing_mefsat_probability)

# ------------------------------------------------------------
# Build probability comparison table
# ------------------------------------------------------------

comparison_probability = overlap_table[
    [
        "Table2_ID",
        "Table2_Name",
        "MEFSAT_MSID",
        "MEFSAT_Name"
    ]
].copy()

# ------------------------------------------------------------
# Add probabilities
# ------------------------------------------------------------

for target in TARGETS:

    # Table 2 lookup
    table2_lookup = (
        table2[
            [
                "Table2_ID",
                table2_probability_columns[target]
            ]
        ]
        .drop_duplicates("Table2_ID")
        .set_index("Table2_ID")
    )

    comparison_probability[
        f"{target}_Table2"
    ] = comparison_probability["Table2_ID"].map(
        table2_lookup[
            table2_probability_columns[target]
        ]
    )

    # MEFSAT lookup
    mefsat_lookup = (
        mefsat[
            [
                "Secondary_Metabolite_Identifier",
                mefsat_probability_columns[target]
            ]
        ]
        .drop_duplicates(
            "Secondary_Metabolite_Identifier"
        )
        .set_index(
            "Secondary_Metabolite_Identifier"
        )
    )

    comparison_probability[
        f"{target}_MEFSAT"
    ] = comparison_probability["MEFSAT_MSID"].map(
        mefsat_lookup[
            mefsat_probability_columns[target]
        ]
    )

# ------------------------------------------------------------
# Missing-value QC
# ------------------------------------------------------------

probability_columns = [
    col
    for col in comparison_probability.columns
    if col.endswith("_Table2")
    or col.endswith("_MEFSAT")
]

print("\nMissing probability values:")
print(
    comparison_probability[
        probability_columns
    ].isna().sum()
)

# ------------------------------------------------------------
# Calculate absolute differences
# ------------------------------------------------------------

difference_columns = []

for target in TARGETS:

    table2_col = f"{target}_Table2"
    mefsat_col = f"{target}_MEFSAT"
    difference_col = f"{target}_Absolute_Difference"

    comparison_probability[difference_col] = (
        comparison_probability[table2_col]
        -
        comparison_probability[mefsat_col]
    ).abs()

    difference_columns.append(difference_col)

# Mean absolute difference per compound
comparison_probability["Mean_Absolute_Difference"] = (
    comparison_probability[difference_columns].mean(axis=1)
)

# Maximum difference per compound
comparison_probability["Maximum_Absolute_Difference"] = (
    comparison_probability[difference_columns].max(axis=1)
)

# ------------------------------------------------------------
# Display probability comparison
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PROBABILITY COMPARISON")
print("=" * 70)

display(comparison_probability)

# ------------------------------------------------------------
# Overall probability agreement summary
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PROBABILITY AGREEMENT SUMMARY")
print("=" * 70)

all_differences = (
    comparison_probability[difference_columns]
    .to_numpy()
)

print(
    f"Total probability comparisons : "
    f"{all_differences.size}"
)

print(
    f"Mean absolute difference      : "
    f"{all_differences.mean():.6f}"
)

print(
    f"Maximum absolute difference   : "
    f"{all_differences.max():.6f}"
)

print(
    f"Minimum absolute difference   : "
    f"{all_differences.min():.6f}"
)

print("\nMean probability difference by compound:")

display(
    comparison_probability[
        [
            "Table2_ID",
            "Table2_Name",
            "MEFSAT_MSID",
            "Mean_Absolute_Difference",
            "Maximum_Absolute_Difference"
        ]
    ]
    .sort_values(
        "Mean_Absolute_Difference",
        ascending=False
    )
)

print("=" * 70)
print("NO SOURCE DATA MODIFIED")
print("=" * 70)

In [ ]:
# ============================================================
# VS-04 — CELL 24
# Build combined 290-compound Ganoderma prediction matrix
# ============================================================

print("=" * 70)
print("VS-04 — COMBINED GANODERMA PREDICTION MATRIX")
print("=" * 70)

# ------------------------------------------------------------
# Target definitions
# ------------------------------------------------------------

TARGETS = [
    "AChE",
    "BChE",
    "M2",
    "NMDAR",
    "5HT6",
    "GSK3B",
    "MAOB",
    "PDE",
    "TNFA",
    "iNOS"
]

# ------------------------------------------------------------
# Confirm source sizes
# ------------------------------------------------------------

print("\nSource datasets:")
print(f"Table 2 compounds : {len(table2)}")
print(f"MEFSAT compounds  : {len(mefsat)}")
print(f"Validated overlap : {len(overlap_table)}")

# ------------------------------------------------------------
# Create validated mapping dictionaries
# Table 2 ID -> MEFSAT MSID
# ------------------------------------------------------------

table2_to_msid = dict(
    zip(
        overlap_table["Table2_ID"],
        overlap_table["MEFSAT_MSID"]
    )
)

# MEFSAT MSIDs represented in the overlap
overlap_msids = set(
    overlap_table["MEFSAT_MSID"]
)

overlap_table2_ids = set(
    overlap_table["Table2_ID"]
)

# ------------------------------------------------------------
# Prepare MEFSAT records
# ------------------------------------------------------------

combined_mefsat = mefsat.copy()

combined_mefsat["Combined_ID"] = (
    combined_mefsat[
        "Secondary_Metabolite_Identifier"
    ]
)

combined_mefsat["Combined_Name"] = (
    combined_mefsat[
        "Secondary_Metabolite_Name"
    ]
)

combined_mefsat["Prediction_Source"] = "MEFSAT"

# ------------------------------------------------------------
# Prepare Table 2 records
# ------------------------------------------------------------

table2_only = table2[
    ~table2["Table2_ID"].isin(overlap_table2_ids)
].copy()

print(
    f"\nTable 2-only compounds : {len(table2_only)}"
)

print(
    f"MEFSAT-only compounds  : "
    f"{len(mefsat) - len(overlap_msids)}"
)

# ------------------------------------------------------------
# Convert Table 2-only compounds into the same structure
# ------------------------------------------------------------

table2_only_combined = pd.DataFrame()

table2_only_combined["Combined_ID"] = (
    "TABLE2_" +
    table2_only["Table2_ID"].astype(str)
)

table2_only_combined["Combined_Name"] = (
    table2_only["Verified_Name"]
)

table2_only_combined["Prediction_Source"] = (
    "Table2"
)

# Add prediction + probability fields
for target in TARGETS:

    table2_only_combined[
        f"{target}_Prediction"
    ] = table2_only[
        f"{target}_Prediction"
    ].values

    table2_only_combined[
        f"{target}_Probability_Class1"
    ] = table2_only[
        f"{target}_Probability"
    ].values

# ------------------------------------------------------------
# Build MEFSAT prediction/probability fields
# ------------------------------------------------------------

mefsat_prediction_columns = [
    f"{target}_Prediction"
    for target in TARGETS
]

mefsat_probability_columns = [
    f"{target}_Probability_Class1"
    for target in TARGETS
]

combined_mefsat = combined_mefsat[
    [
        "Combined_ID",
        "Combined_Name",
        "Prediction_Source"
    ] +
    mefsat_prediction_columns +
    mefsat_probability_columns
].copy()

# ------------------------------------------------------------
# Keep only the required Table 2 fields
# ------------------------------------------------------------

table2_only_combined = table2_only_combined[
    [
        "Combined_ID",
        "Combined_Name",
        "Prediction_Source"
    ] +
    mefsat_prediction_columns +
    mefsat_probability_columns
].copy()

# ------------------------------------------------------------
# Combine the two unique sets
# ------------------------------------------------------------

combined_predictions = pd.concat(
    [
        combined_mefsat,
        table2_only_combined
    ],
    ignore_index=True
)

# ------------------------------------------------------------
# Add source-count information
# ------------------------------------------------------------

combined_predictions["Source_Count"] = (
    combined_predictions["Prediction_Source"]
    .map(
        {
            "MEFSAT": 1,
            "Table2": 1
        }
    )
)

# ------------------------------------------------------------
# Basic QC
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("COMBINED DATASET QC")
print("=" * 70)

print(
    f"Combined rows : {len(combined_predictions)}"
)

print(
    f"Combined columns : "
    f"{len(combined_predictions.columns)}"
)

print("\nPrediction source:")
print(
    combined_predictions[
        "Prediction_Source"
    ].value_counts()
)

print("\nDuplicate Combined_ID values:")
print(
    combined_predictions[
        "Combined_ID"
    ].duplicated()
    .sum()
)

# ------------------------------------------------------------
# Missing prediction/probability QC
# ------------------------------------------------------------

combined_prediction_columns = [
    f"{target}_Prediction"
    for target in TARGETS
]

combined_probability_columns = [
    f"{target}_Probability_Class1"
    for target in TARGETS
]

print("\nMissing prediction values:")
print(
    combined_predictions[
        combined_prediction_columns
    ].isna().sum()
)

print("\nMissing probability values:")
print(
    combined_predictions[
        combined_probability_columns
    ].isna().sum()
)

# ------------------------------------------------------------
# Prediction count by target
# ------------------------------------------------------------

print("\nPredicted class-1 counts:")
print(
    combined_predictions[
        combined_prediction_columns
    ].sum()
)

# ------------------------------------------------------------
# Display first rows
# ------------------------------------------------------------

print("\nFirst 10 combined records:")

display(
    combined_predictions[
        [
            "Combined_ID",
            "Combined_Name",
            "Prediction_Source"
        ] +
        combined_prediction_columns
    ].head(10)
)

print("=" * 70)
print("COMBINED PREDICTION MATRIX CREATED")
print("No source dataset modified.")
print("No new predictions performed.")
print("=" * 70)

In [ ]:
# ============================================================
# VS-04 — CELL 25
# Extract all predicted target associations
# ============================================================

print("=" * 70)
print("VS-04 — COMBINED GANODERMA PREDICTED-HIT EXTRACTION")
print("=" * 70)

# ------------------------------------------------------------
# Extract predicted hits
# ------------------------------------------------------------

hit_rows = []

for _, row in combined_predictions.iterrows():

    for target in TARGETS:

        prediction_col = f"{target}_Prediction"
        probability_col = f"{target}_Probability_Class1"

        if row[prediction_col] == 1:

            hit_rows.append({
                "Combined_ID": row["Combined_ID"],
                "Compound_Name": row["Combined_Name"],
                "Prediction_Source": row["Prediction_Source"],
                "Target": target,
                "Predicted_Class": int(row[prediction_col]),
                "Active_Probability": row[probability_col]
            })

combined_hits = pd.DataFrame(hit_rows)

# ------------------------------------------------------------
# Handle empty result safely
# ------------------------------------------------------------

if combined_hits.empty:

    print("\nNo predicted class-1 associations found.")

else:

    # --------------------------------------------------------
    # Sort by compound, then target
    # --------------------------------------------------------

    combined_hits = combined_hits.sort_values(
        [
            "Combined_ID",
            "Target"
        ]
    ).reset_index(drop=True)

    # --------------------------------------------------------
    # Summary
    # --------------------------------------------------------

    print("\nPredicted hits by target:")

    target_hit_counts = (
        combined_hits["Target"]
        .value_counts()
        .reindex(TARGETS, fill_value=0)
    )

    print(target_hit_counts)

    print(
        f"\nTotal predicted compound-target associations : "
        f"{len(combined_hits)}"
    )

    print(
        f"Unique compounds among hits                 : "
        f"{combined_hits['Combined_ID'].nunique()}"
    )

    print(
        f"Unique targets among hits                   : "
        f"{combined_hits['Target'].nunique()}"
    )

    # --------------------------------------------------------
    # Source distribution
    # --------------------------------------------------------

    print("\nPredicted hits by source:")

    print(
        combined_hits[
            "Prediction_Source"
        ].value_counts()
    )

    # --------------------------------------------------------
    # Display all hits
    # --------------------------------------------------------

    print("\n" + "=" * 70)
    print("ALL COMBINED PREDICTED HITS")
    print("=" * 70)

    display(combined_hits)

    # --------------------------------------------------------
    # Probability summary
    # --------------------------------------------------------

    print("\n" + "=" * 70)
    print("ACTIVE-PROBABILITY SUMMARY")
    print("=" * 70)

    print(
        combined_hits[
            "Active_Probability"
        ].describe()
    )

# ------------------------------------------------------------
# Final QC
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PREDICTED-HIT EXTRACTION COMPLETE")
print("No probability threshold applied.")
print("Hit criterion: Predicted_Class == 1")
print("No compounds excluded.")
print("No ranking performed.")
print("=" * 70)

In [ ]:
# ============================================================
# VS-04 — CELL 26
# Final combined predicted-hit integrity QC
# ============================================================

print("=" * 70)
print("VS-04 — FINAL COMBINED PREDICTED-HIT INTEGRITY QC")
print("=" * 70)

# ------------------------------------------------------------
# Essential columns
# ------------------------------------------------------------

essential_columns = [
    "Combined_ID",
    "Compound_Name",
    "Prediction_Source",
    "Target",
    "Predicted_Class",
    "Active_Probability"
]

print("\nMissing essential values:")
print(
    combined_hits[essential_columns].isna().sum()
)

# ------------------------------------------------------------
# Predicted class validation
# ------------------------------------------------------------

print("\nPredicted class values:")
print(
    combined_hits["Predicted_Class"].value_counts()
)

# ------------------------------------------------------------
# Duplicate compound-target checks
# ------------------------------------------------------------

duplicate_compound_target = combined_hits.duplicated(
    subset=["Combined_ID", "Target"]
).sum()

print(
    "\nDuplicate compound-target associations:",
    duplicate_compound_target
)

# ------------------------------------------------------------
# Unique compound checks
# ------------------------------------------------------------

print(
    "\nTotal predicted associations :",
    len(combined_hits)
)

print(
    "Unique predicted compounds   :",
    combined_hits["Combined_ID"].nunique()
)

print(
    "Unique predicted targets     :",
    combined_hits["Target"].nunique()
)

# ------------------------------------------------------------
# Source-level check
# ------------------------------------------------------------

print("\nPredicted associations by source:")
print(
    combined_hits["Prediction_Source"].value_counts()
)

# ------------------------------------------------------------
# Target-level check
# ------------------------------------------------------------

print("\nPredicted associations by target:")
print(
    combined_hits["Target"]
    .value_counts()
    .reindex(TARGETS, fill_value=0)
)

# ------------------------------------------------------------
# Probability validity
# ------------------------------------------------------------

print("\nProbability validity:")

print(
    "Minimum probability :",
    combined_hits["Active_Probability"].min()
)

print(
    "Maximum probability :",
    combined_hits["Active_Probability"].max()
)

invalid_probability = (
    (combined_hits["Active_Probability"] < 0) |
    (combined_hits["Active_Probability"] > 1)
).sum()

print(
    "Probabilities outside [0, 1] :",
    invalid_probability
)

# ------------------------------------------------------------
# Multi-target compounds
# ------------------------------------------------------------

target_counts_per_compound = (
    combined_hits
    .groupby(
        ["Combined_ID", "Compound_Name"]
    )["Target"]
    .nunique()
    .reset_index(
        name="Number_of_Predicted_Targets"
    )
)

multi_target_compounds = (
    target_counts_per_compound[
        target_counts_per_compound[
            "Number_of_Predicted_Targets"
        ] > 1
    ]
    .sort_values(
        "Number_of_Predicted_Targets",
        ascending=False
    )
)

print("\nMulti-target predicted compounds:")

if multi_target_compounds.empty:
    print("None")

else:
    display(multi_target_compounds)

# ------------------------------------------------------------
# Final table
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL COMBINED PREDICTED-HIT TABLE")
print("=" * 70)

display(
    combined_hits.sort_values(
        [
            "Compound_Name",
            "Target"
        ]
    ).reset_index(drop=True)
)

# ------------------------------------------------------------
# Final pass/fail statement
# ------------------------------------------------------------

qc_pass = (
    combined_hits[essential_columns].isna().sum().sum() == 0
    and combined_hits["Predicted_Class"].eq(1).all()
    and duplicate_compound_target == 0
    and invalid_probability == 0
)

print("\n" + "=" * 70)

if qc_pass:
    print("✓ FINAL COMBINED PREDICTED-HIT QC PASSED")

else:
    print("✗ FINAL COMBINED PREDICTED-HIT QC FAILED")

print("=" * 70)
print("No threshold applied.")
print("No compounds excluded.")
print("No source data modified.")
print("=" * 70)

In [ ]:
# ============================================================
# VS-04 — CELL 27
# Full Ganoderma compound × receptor prediction matrix
# ============================================================

print("=" * 70)
print("VS-04 — FULL GANODERMA × RECEPTOR PREDICTION MATRIX")
print("=" * 70)

# ------------------------------------------------------------
# Build activity matrix
# ------------------------------------------------------------

activity_matrix = combined_predictions[
    [
        "Combined_ID",
        "Combined_Name",
        "Prediction_Source"
    ]
].copy()

# Add prediction class for each target
for target in TARGETS:
    activity_matrix[target] = combined_predictions[
        f"{target}_Prediction"
    ].astype(int)

# ------------------------------------------------------------
# Add number of predicted targets per compound
# ------------------------------------------------------------

activity_matrix["Number_of_Predicted_Targets"] = (
    activity_matrix[TARGETS].sum(axis=1)
)

# ------------------------------------------------------------
# QC
# ------------------------------------------------------------

print("\nMatrix dimensions:")
print(f"Rows    : {len(activity_matrix)}")
print(f"Columns : {len(activity_matrix.columns)}")

print("\nExpected rows:")
print("290")

print("\nDuplicate compound IDs:")
print(
    activity_matrix["Combined_ID"].duplicated().sum()
)

print("\nMissing values:")
print(
    activity_matrix[
        TARGETS
    ].isna().sum()
)

# ------------------------------------------------------------
# Binary-value validation
# ------------------------------------------------------------

invalid_values = {}

for target in TARGETS:

    values = set(
        activity_matrix[target].dropna().unique()
    )

    invalid = values - {0, 1}

    if invalid:
        invalid_values[target] = invalid

print("\nInvalid prediction values:")
print(invalid_values)

# ------------------------------------------------------------
# Target-level predicted activity counts
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PREDICTED ACTIVITY COUNT BY TARGET")
print("=" * 70)

target_counts = (
    activity_matrix[TARGETS]
    .sum()
    .sort_values(ascending=False)
)

print(target_counts)

# ------------------------------------------------------------
# Compound-level predicted target counts
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("COMPOUND TARGET-COUNT DISTRIBUTION")
print("=" * 70)

print(
    activity_matrix[
        "Number_of_Predicted_Targets"
    ].value_counts()
    .sort_index()
)

# ------------------------------------------------------------
# Compounds with at least one predicted target
# ------------------------------------------------------------

predicted_compounds = activity_matrix[
    activity_matrix[
        "Number_of_Predicted_Targets"
    ] > 0
].copy()

print(
    "\nCompounds with ≥1 predicted target:",
    len(predicted_compounds)
)

print(
    "Compounds with no predicted targets:",
    len(activity_matrix) -
    len(predicted_compounds)
)

# ------------------------------------------------------------
# Display compounds with predicted activity
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("COMPOUNDS WITH PREDICTED TARGET ACTIVITY")
print("=" * 70)

display(
    predicted_compounds.sort_values(
        [
            "Number_of_Predicted_Targets",
            "Combined_Name"
        ],
        ascending=[False, True]
    )
)

# ------------------------------------------------------------
# Final QC
# ------------------------------------------------------------

matrix_qc_pass = (
    len(activity_matrix) == 290
    and activity_matrix[
        "Combined_ID"
    ].duplicated().sum() == 0
    and activity_matrix[
        TARGETS
    ].isna().sum().sum() == 0
    and len(invalid_values) == 0
)

print("\n" + "=" * 70)

if matrix_qc_pass:
    print("✓ FULL ACTIVITY MATRIX QC PASSED")
else:
    print("✗ FULL ACTIVITY MATRIX QC FAILED")

print("=" * 70)
print("No new predictions performed.")
print("No thresholds applied.")
print("No source data modified.")
print("=" * 70)

In [ ]:
# ============================================================
# VS-04 — CELL 28
# Full Ganoderma × receptor active-probability matrix
# ============================================================

print("=" * 70)
print("VS-04 — FULL GANODERMA × RECEPTOR ACTIVE-PROBABILITY MATRIX")
print("=" * 70)

# ------------------------------------------------------------
# Build probability matrix using the same 290 compounds
# ------------------------------------------------------------

probability_matrix = combined_predictions[
    [
        "Combined_ID",
        "Combined_Name",
        "Prediction_Source"
    ]
].copy()

# Add class-1 probability for each target
for target in TARGETS:

    probability_matrix[target] = combined_predictions[
        f"{target}_Probability_Class1"
    ].astype(float)

# ------------------------------------------------------------
# QC: dimensions
# ------------------------------------------------------------

print("\nMatrix dimensions:")
print(f"Rows    : {len(probability_matrix)}")
print(f"Columns : {len(probability_matrix.columns)}")

print("\nExpected rows:")
print("290")

# ------------------------------------------------------------
# QC: duplicate compounds
# ------------------------------------------------------------

print("\nDuplicate compound IDs:")
print(
    probability_matrix[
        "Combined_ID"
    ].duplicated().sum()
)

# ------------------------------------------------------------
# QC: missing values
# ------------------------------------------------------------

print("\nMissing probability values:")

missing_probabilities = (
    probability_matrix[TARGETS]
    .isna()
    .sum()
)

print(missing_probabilities)

# ------------------------------------------------------------
# QC: probability range
# ------------------------------------------------------------

invalid_probability_values = {}

for target in TARGETS:

    values = probability_matrix[target]

    invalid = values[
        (values < 0) |
        (values > 1)
    ]

    if len(invalid) > 0:
        invalid_probability_values[target] = len(invalid)

print("\nProbability values outside [0, 1]:")
print(invalid_probability_values)

# ------------------------------------------------------------
# Overall probability range
# ------------------------------------------------------------

overall_min = (
    probability_matrix[TARGETS]
    .min()
    .min()
)

overall_max = (
    probability_matrix[TARGETS]
    .max()
    .max()
)

print("\nOverall probability range:")
print(f"Minimum : {overall_min:.6f}")
print(f"Maximum : {overall_max:.6f}")

# ------------------------------------------------------------
# Target-level probability summary
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("TARGET-LEVEL PROBABILITY SUMMARY")
print("=" * 70)

target_probability_summary = pd.DataFrame({
    "Minimum": probability_matrix[TARGETS].min(),
    "Maximum": probability_matrix[TARGETS].max(),
    "Mean": probability_matrix[TARGETS].mean(),
    "Median": probability_matrix[TARGETS].median(),
    "95th_Percentile": probability_matrix[TARGETS].quantile(0.95)
})

display(target_probability_summary)

# ------------------------------------------------------------
# Check correspondence with activity matrix
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("ACTIVITY ↔ PROBABILITY MATRIX CORRESPONDENCE")
print("=" * 70)

same_ids = (
    probability_matrix["Combined_ID"].tolist()
    ==
    activity_matrix["Combined_ID"].tolist()
)

same_names = (
    probability_matrix["Combined_Name"].tolist()
    ==
    activity_matrix["Combined_Name"].tolist()
)

print(
    "Compound ID order identical:",
    same_ids
)

print(
    "Compound name order identical:",
    same_names
)

# ------------------------------------------------------------
# Display first 10 rows
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FIRST 10 COMPOUNDS")
print("=" * 70)

display(
    probability_matrix.head(10)
)

# ------------------------------------------------------------
# Final QC
# ------------------------------------------------------------

probability_qc_pass = (
    len(probability_matrix) == 290
    and probability_matrix[
        "Combined_ID"
    ].duplicated().sum() == 0
    and missing_probabilities.sum() == 0
    and len(invalid_probability_values) == 0
    and same_ids
    and same_names
)

print("\n" + "=" * 70)

if probability_qc_pass:
    print("✓ FULL PROBABILITY MATRIX QC PASSED")
else:
    print("✗ FULL PROBABILITY MATRIX QC FAILED")

print("=" * 70)
print("No new predictions performed.")
print("No probability threshold applied.")
print("No source data modified.")
print("=" * 70)

In [ ]:
# ============================================================
# VS-04 — CELL 29
# Top 10 compounds by active probability for each target
# ============================================================

print("=" * 70)
print("VS-04 — TOP 10 COMPOUNDS BY ACTIVE PROBABILITY")
print("=" * 70)

top10_by_target = {}

for target in TARGETS:

    target_table = probability_matrix[
        [
            "Combined_ID",
            "Combined_Name",
            "Prediction_Source",
            target
        ]
    ].copy()

    target_table = target_table.sort_values(
        by=target,
        ascending=False
    ).reset_index(drop=True)

    target_table.insert(
        0,
        "Rank",
        range(1, len(target_table) + 1)
    )

    target_table = target_table.rename(
        columns={target: "Active_Probability"}
    )

    # Add predicted class from validated activity matrix
    target_table["Predicted_Class"] = (
        activity_matrix
        .set_index("Combined_ID")
        .loc[
            target_table["Combined_ID"],
            target
        ]
        .values
    )

    # Keep top 10 only
    top10_by_target[target] = target_table.head(10).copy()

    print("\n" + "-" * 70)
    print(f"TARGET: {target}")
    print("-" * 70)

    display(
        top10_by_target[target]
    )

# ------------------------------------------------------------
# Create one combined top-10 table
# ------------------------------------------------------------

top10_combined = pd.concat(
    [
        table.assign(Target=target)
        for target, table in top10_by_target.items()
    ],
    ignore_index=True
)

# Reorder columns
top10_combined = top10_combined[
    [
        "Target",
        "Rank",
        "Combined_ID",
        "Combined_Name",
        "Prediction_Source",
        "Predicted_Class",
        "Active_Probability"
    ]
]

# ------------------------------------------------------------
# QC
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("TOP-10 RANKING QC")
print("=" * 70)

print(
    "Number of targets:",
    top10_combined["Target"].nunique()
)

print(
    "Rows in combined top-10 table:",
    len(top10_combined)
)

print(
    "Expected rows:",
    len(TARGETS) * 10
)

print(
    "Missing values:"
)

print(
    top10_combined[
        [
            "Target",
            "Rank",
            "Combined_ID",
            "Combined_Name",
            "Prediction_Source",
            "Predicted_Class",
            "Active_Probability"
        ]
    ].isna().sum()
)

# Check rank integrity
rank_check = (
    top10_combined
    .groupby("Target")["Rank"]
    .apply(lambda x: list(x) == list(range(1, 11)))
)

print("\nRank integrity:")
print(rank_check)

# Check probability ordering
ordering_check = {}

for target in TARGETS:

    values = top10_by_target[target][
        "Active_Probability"
    ].tolist()

    ordering_check[target] = all(
        values[i] >= values[i + 1]
        for i in range(len(values) - 1)
    )

print("\nProbability descending-order check:")
print(ordering_check)

# Final QC
top10_qc_pass = (
    top10_combined["Target"].nunique() == len(TARGETS)
    and len(top10_combined) == len(TARGETS) * 10
    and top10_combined.isna().sum().sum() == 0
    and rank_check.all()
    and all(ordering_check.values())
)

print("\n" + "=" * 70)

if top10_qc_pass:
    print("✓ TOP-10 PROBABILITY RANKING QC PASSED")
else:
    print("✗ TOP-10 PROBABILITY RANKING QC FAILED")

print("=" * 70)
print("No new predictions performed.")
print("No probability threshold applied.")
print("No source data modified.")
print("=" * 70)

In [ ]:
# ============================================================
# VS-04 — CELL 30
# Probability-prioritised class-0 candidates
# ============================================================

print("=" * 70)
print("VS-04 — PROBABILITY-PRIORITISED CLASS-0 CANDIDATES")
print("=" * 70)

# ------------------------------------------------------------
# Candidate threshold
# ------------------------------------------------------------

PROBABILITY_CANDIDATE_THRESHOLD = 0.30

print(
    "\nCandidate probability threshold:",
    PROBABILITY_CANDIDATE_THRESHOLD
)

# ------------------------------------------------------------
# Build candidate tables for each target
# ------------------------------------------------------------

near_hit_by_target = {}

for target in TARGETS:

    # Merge probability and predicted class
    target_candidates = probability_matrix[
        [
            "Combined_ID",
            "Combined_Name",
            "Prediction_Source",
            target
        ]
    ].copy()

    target_candidates = target_candidates.rename(
        columns={
            target: "Active_Probability"
        }
    )

    target_candidates["Predicted_Class"] = (
        activity_matrix
        .set_index("Combined_ID")
        .loc[
            target_candidates["Combined_ID"],
            target
        ]
        .values
    )

    # Keep ONLY class-0 compounds at/above threshold
    target_candidates = target_candidates[
        (target_candidates["Predicted_Class"] == 0)
        &
        (
            target_candidates["Active_Probability"]
            >= PROBABILITY_CANDIDATE_THRESHOLD
        )
    ].copy()

    target_candidates = target_candidates.sort_values(
        "Active_Probability",
        ascending=False
    ).reset_index(drop=True)

    target_candidates.insert(
        0,
        "Rank",
        range(1, len(target_candidates) + 1)
    )

    near_hit_by_target[target] = target_candidates

    print("\n" + "-" * 70)
    print(f"TARGET: {target}")
    print("-" * 70)

    print(
        "Number of class-0 candidates:",
        len(target_candidates)
    )

    if len(target_candidates) > 0:
        display(target_candidates)
    else:
        print("None")

# ------------------------------------------------------------
# Combined candidate table
# ------------------------------------------------------------

near_hit_combined = pd.concat(
    [
        table.assign(Target=target)
        for target, table in near_hit_by_target.items()
        if len(table) > 0
    ],
    ignore_index=True
)

if len(near_hit_combined) > 0:

    near_hit_combined = near_hit_combined[
        [
            "Target",
            "Rank",
            "Combined_ID",
            "Combined_Name",
            "Prediction_Source",
            "Predicted_Class",
            "Active_Probability"
        ]
    ]

else:

    near_hit_combined = pd.DataFrame(
        columns=[
            "Target",
            "Rank",
            "Combined_ID",
            "Combined_Name",
            "Prediction_Source",
            "Predicted_Class",
            "Active_Probability"
        ]
    )

# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PROBABILITY-PRIORITISED CLASS-0 SUMMARY")
print("=" * 70)

print(
    "Total candidate associations:",
    len(near_hit_combined)
)

print(
    "Unique candidate compounds:",
    near_hit_combined["Combined_ID"].nunique()
)

if len(near_hit_combined) > 0:

    print("\nCandidates by target:")
    print(
        near_hit_combined["Target"]
        .value_counts()
        .reindex(TARGETS, fill_value=0)
    )

    print("\nHighest candidate probability:")
    display(
        near_hit_combined.loc[
            near_hit_combined["Active_Probability"].idxmax()
        ].to_frame().T
    )

# ------------------------------------------------------------
# Integrity checks
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("CELL 30 QC")
print("=" * 70)

if len(near_hit_combined) > 0:

    print(
        "\nPredicted class values:"
    )
    print(
        near_hit_combined[
            "Predicted_Class"
        ].value_counts()
    )

    print(
        "\nProbabilities below threshold:"
    )
    print(
        (
            near_hit_combined[
                "Active_Probability"
            ]
            < PROBABILITY_CANDIDATE_THRESHOLD
        ).sum()
    )

    print(
        "\nProbabilities outside [0, 1]:"
    )
    print(
        (
            (
                near_hit_combined[
                    "Active_Probability"
                ] < 0
            )
            |
            (
                near_hit_combined[
                    "Active_Probability"
                ] > 1
            )
        ).sum()
    )

    print(
        "\nDuplicate compound-target associations:"
    )
    print(
        near_hit_combined.duplicated(
            subset=[
                "Combined_ID",
                "Target"
            ]
        ).sum()
    )

# ------------------------------------------------------------
# Final QC
# ------------------------------------------------------------

qc_pass = True

if len(near_hit_combined) > 0:

    qc_pass = (
        near_hit_combined[
            "Predicted_Class"
        ].eq(0).all()
        and
        (
            near_hit_combined[
                "Active_Probability"
            ]
            >= PROBABILITY_CANDIDATE_THRESHOLD
        ).all()
        and
        (
            near_hit_combined[
                "Active_Probability"
            ].between(0, 1).all()
        )
        and
        near_hit_combined.duplicated(
            subset=[
                "Combined_ID",
                "Target"
            ]
        ).sum() == 0
    )

print("\n" + "=" * 70)

if qc_pass:
    print("✓ CELL 30 QC PASSED")
else:
    print("✗ CELL 30 QC FAILED")

print("=" * 70)
print("These are NOT predicted hits.")
print("They remain Predicted_Class = 0.")
print("No model predictions performed.")
print("No source data modified.")
print("=" * 70)

In [ ]:
# ============================================================
# VS-04 — CELL 31
# FINAL COMPOUND-LEVEL SCREENING SUMMARY
# ============================================================

print("=" * 70)
print("VS-04 — FINAL COMPOUND-LEVEL SCREENING SUMMARY")
print("=" * 70)

# ------------------------------------------------------------
# 1. Start from the validated combined activity matrix
# ------------------------------------------------------------

final_summary = activity_matrix[
    [
        "Combined_ID",
        "Combined_Name",
        "Prediction_Source"
    ] + TARGETS
].copy()

# ------------------------------------------------------------
# 2. Number of predicted targets per compound
# ------------------------------------------------------------

final_summary["Number_of_Predicted_Targets"] = (
    final_summary[TARGETS]
    .sum(axis=1)
)

# ------------------------------------------------------------
# 3. Predicted receptor list
# ------------------------------------------------------------

def get_predicted_targets(row):
    return ", ".join(
        [
            target
            for target in TARGETS
            if row[target] == 1
        ]
    )

final_summary["Predicted_Targets"] = (
    final_summary.apply(
        get_predicted_targets,
        axis=1
    )
)

# ------------------------------------------------------------
# 4. Assign primary screening tier
# ------------------------------------------------------------

def assign_screening_tier(row):

    n_targets = row["Number_of_Predicted_Targets"]

    if n_targets >= 1:
        return "Predicted hit"

    return "No predicted activity"

final_summary["Screening_Tier"] = (
    final_summary.apply(
        assign_screening_tier,
        axis=1
    )
)

# ------------------------------------------------------------
# 5. Add highest active probability
# ------------------------------------------------------------

final_summary["Highest_Active_Probability"] = 0.0
final_summary["Highest_Probability_Target"] = ""

for idx, row in final_summary.iterrows():

    compound_id = row["Combined_ID"]

    probability_row = probability_matrix[
        probability_matrix["Combined_ID"] == compound_id
    ]

    if len(probability_row) != 1:
        raise ValueError(
            f"Expected exactly one probability row for {compound_id}, "
            f"found {len(probability_row)}"
        )

    probabilities = probability_row.iloc[0]

    target_probabilities = {
        target: float(probabilities[target])
        for target in TARGETS
    }

    highest_target = max(
        target_probabilities,
        key=target_probabilities.get
    )

    final_summary.loc[
        idx,
        "Highest_Active_Probability"
    ] = target_probabilities[highest_target]

    final_summary.loc[
        idx,
        "Highest_Probability_Target"
    ] = highest_target

# ------------------------------------------------------------
# 6. Reorder columns
# ------------------------------------------------------------

final_summary = final_summary[
    [
        "Combined_ID",
        "Combined_Name",
        "Prediction_Source",
        "Predicted_Targets",
        "Number_of_Predicted_Targets",
        "Highest_Probability_Target",
        "Highest_Active_Probability",
        "Screening_Tier"
    ]
]

# ------------------------------------------------------------
# 7. Display predicted-hit compounds first
# ------------------------------------------------------------

final_summary = final_summary.sort_values(
    by=[
        "Number_of_Predicted_Targets",
        "Highest_Active_Probability"
    ],
    ascending=[
        False,
        False
    ]
).reset_index(drop=True)

print("\nFINAL COMPOUND-LEVEL SUMMARY:")
display(final_summary)

# ------------------------------------------------------------
# 8. Summary statistics
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL SUMMARY STATISTICS")
print("=" * 70)

print(
    "Total compounds:",
    len(final_summary)
)

print(
    "Compounds with ≥1 predicted target:",
    (
        final_summary["Number_of_Predicted_Targets"] >= 1
    ).sum()
)

print(
    "Compounds with no predicted targets:",
    (
        final_summary["Number_of_Predicted_Targets"] == 0
    ).sum()
)

print("\nScreening tier:")
print(
    final_summary["Screening_Tier"]
    .value_counts()
)

print("\nPrediction source:")
print(
    final_summary["Prediction_Source"]
    .value_counts()
)

print("\n" + "=" * 70)
print("PREDICTED-HIT COMPOUND SUMMARY")
print("=" * 70)

predicted_hit_compounds = final_summary[
    final_summary["Number_of_Predicted_Targets"] >= 1
].copy()

display(predicted_hit_compounds)

# ------------------------------------------------------------
# 9. Integrity QC
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("CELL 31 — FINAL SUMMARY QC")
print("=" * 70)

print("\nRows:", len(final_summary))

print(
    "Duplicate Combined_ID values:",
    final_summary["Combined_ID"].duplicated().sum()
)

print("\nMissing values:")
print(
    final_summary.isna().sum()
)

print("\nInvalid target counts:")
print(
    (
        (final_summary["Number_of_Predicted_Targets"] < 0)
        |
        (final_summary["Number_of_Predicted_Targets"] > len(TARGETS))
    ).sum()
)

print("\nHighest probability range:")
print(
    f"{final_summary['Highest_Active_Probability'].min():.6f}"
    " - "
    f"{final_summary['Highest_Active_Probability'].max():.6f}"
)

# ------------------------------------------------------------
# Expected values
# ------------------------------------------------------------

expected_rows = 290
expected_predicted_hit_compounds = 5

qc_pass = (
    len(final_summary) == expected_rows
    and final_summary["Combined_ID"].duplicated().sum() == 0
    and final_summary.isna().sum().sum() == 0
    and (
        final_summary["Number_of_Predicted_Targets"]
        .between(0, len(TARGETS))
        .all()
    )
    and (
        final_summary[
            "Highest_Active_Probability"
        ]
        .between(0, 1)
        .all()
    )
    and (
        len(predicted_hit_compounds)
        == expected_predicted_hit_compounds
    )
)

print("\n" + "=" * 70)

if qc_pass:
    print("✓ CELL 31 FINAL SUMMARY QC PASSED")
else:
    print("✗ CELL 31 FINAL SUMMARY QC FAILED")

print("=" * 70)
print("No new predictions performed.")
print("No thresholds applied.")
print("No source data modified.")
print("=" * 70)

In [ ]:
# ============================================================
# VS-04 — SAVE FINAL OVERALL SCREENING RESULTS
# ============================================================

from pathlib import Path

# ------------------------------------------------------------
# Output directory
# ------------------------------------------------------------

FINAL_OUTPUT_DIR = Path(
    "/content/drive/MyDrive/PhD_ML_Project/VS-04_Batch_03_MEFSAT/03_Prediction"
)

FINAL_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# ------------------------------------------------------------
# Save complete 290-compound overall summary
# ------------------------------------------------------------

FINAL_SUMMARY_OUTPUT = (
    FINAL_OUTPUT_DIR /
    "Batch03_MEFSAT_Overall_290_Compound_Screening_Summary.csv"
)

final_summary.to_csv(
    FINAL_SUMMARY_OUTPUT,
    index=False
)

# ------------------------------------------------------------
# Save predicted-hit compound summary
# ------------------------------------------------------------

FINAL_HITS_OUTPUT = (
    FINAL_OUTPUT_DIR /
    "Batch03_MEFSAT_Overall_Predicted_Hits.csv"
)

predicted_hit_compounds.to_csv(
    FINAL_HITS_OUTPUT,
    index=False
)

# ------------------------------------------------------------
# Verification
# ------------------------------------------------------------

print("=" * 70)
print("FINAL OVERALL RESULTS — CSV SAVE VERIFICATION")
print("=" * 70)

print("\nOverall summary:")
print("File:", FINAL_SUMMARY_OUTPUT)
print("Exists:", FINAL_SUMMARY_OUTPUT.exists())
print("Rows:", len(final_summary))
print("Columns:", len(final_summary.columns))

print("\nPredicted-hit summary:")
print("File:", FINAL_HITS_OUTPUT)
print("Exists:", FINAL_HITS_OUTPUT.exists())
print("Rows:", len(predicted_hit_compounds))
print("Columns:", len(predicted_hit_compounds.columns))

print("\n✓ FINAL OVERALL CSV FILES SAVED")